<a href="https://colab.research.google.com/github/tettehdaniel/python-labs/blob/main/Notebooks/Notebook04_DataManipulation2_SV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 04 — Data Manipulation Two

**Main Objective**

1. Grouping
2. Variable Creation (Adding Columns)

## Setup

Please run the setup code below

In [1]:
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py

from funs import *

In [2]:
import numpy as np
import polars as pl

from plotnine import *
from polars import col as c
theme_set(theme_minimal())

path = "https://raw.githubusercontent.com/ajcollins16/DSST289_Fall2026_AJC/refs/heads/main/"

In [3]:
dat = pl.read_csv(path + "Data/countries.csv").drop(c.lang)

## Grouping and Variable Creation

Today we will continue to work through some data manipulation concepts. The data is now different than what we have seen thus far. Specifically the "countries" dataset is one where we have 135 countries listed by a slew of variables. Specifically information on name of country and region, geographical coordinates (latitude and longitude), life expectancy, happiness rating, population (in millions), the GDP per capita, and others.

Although we will get some more practice with the sorting, selecting, and filtering functions, we will more importantly learn about grouping and variable creating. Specifically:

* Grouping &rarr; used to split the dataset into groups based on the values of one or more columns to better summarize (or analyze) the groups.
* Variable Creation &rarr; simple practice of adding a new variable to a dataset often through the calculation of already existing columns.

### Questions

1. Start by finding the country with the highest life expectancy (displaying only the one row)

In [4]:
dat

shape: (135, 14)
┌─────┬─────────────────┬──────────┬─────────────────┬───┬──────┬───────┬───────────┬──────────────┐
│ iso ┆ full_name       ┆ region   ┆ subregion       ┆ … ┆ gini ┆ happy ┆ cellphone ┆ water_access │
│ --- ┆ ---             ┆ ---      ┆ ---             ┆   ┆ ---  ┆ ---   ┆ ---       ┆ ---          │
│ str ┆ str             ┆ str      ┆ str             ┆   ┆ f64  ┆ f64   ┆ f64       ┆ f64          │
╞═════╪═════════════════╪══════════╪═════════════════╪═══╪══════╪═══════╪═══════════╪══════════════╡
│ SEN ┆ Senegal         ┆ Africa   ┆ Western Africa  ┆ … ┆ 38.1 ┆ 50.93 ┆ 66.0      ┆ 54.93987     │
│ VEN ┆ Venezuela,      ┆ Americas ┆ South America   ┆ … ┆ 44.8 ┆ 57.65 ┆ 96.8      ┆ 95.66913     │
│     ┆ Bolivarian      ┆          ┆                 ┆   ┆      ┆       ┆           ┆              │
│     ┆ Republic…       ┆          ┆                 ┆   ┆      ┆       ┆           ┆              │
│ FIN ┆ Finland         ┆ Europe   ┆ Northern Europe ┆ … ┆ 27.7 ┆ 76.99 ┆ 156.4     ┆ 99.44798     │
│ USA ┆ United States   ┆ Americas ┆ Northern        ┆ … ┆ 47.7 ┆ 65.21 ┆ 91.7      ┆ 99.72235     │
│     ┆ of America      ┆          ┆ America         ┆   ┆      ┆       ┆           ┆              │
│ LKA ┆ Sri Lanka       ┆ Asia     ┆ Southern Asia   ┆ … ┆ 39.3 ┆ 36.02 ┆ 83.1      ┆ 90.77437     │
│ …   ┆ …               ┆ …        ┆ …               ┆ … ┆ …    ┆ …     ┆ …         ┆ …            │
│ ALB ┆ Albania         ┆ Europe   ┆ Southern Europe ┆ … ┆ 30.8 ┆ 54.45 ┆ 91.9      ┆ 98.5473      │
│ MYS ┆ Malaysia        ┆ Asia     ┆ South-eastern   ┆ … ┆ 46.2 ┆ 58.68 ┆ 118.2     ┆ 95.69194     │
│     ┆                 ┆          ┆ Asia            ┆   ┆      ┆       ┆           ┆              │
│ SLV ┆ El Salvador     ┆ Americas ┆ Central America ┆ … ┆ 38.3 ┆ 64.82 ┆ 126.9     ┆ 86.19786     │
│ CYP ┆ Cyprus          ┆ Asia     ┆ Western Asia    ┆ … ┆ 31.2 ┆ 60.71 ┆ 123.1     ┆ 99.41781     │
│ PAK ┆ Pakistan        ┆ Asia     ┆ Southern Asia   ┆ … ┆ 29.6 ┆ 45.49 ┆ 49.8      ┆ 61.92651     │
└─────┴─────────────────┴──────────┴─────────────────┴───┴──────┴───────┴───────────┴──────────────┘

In [6]:
(
    dat
    .sort(c.lexp, descending=True)
)

shape: (135, 14)
┌─────┬──────────────┬────────┬────────────────────┬───┬──────┬───────┬───────────┬──────────────┐
│ iso ┆ full_name    ┆ region ┆ subregion          ┆ … ┆ gini ┆ happy ┆ cellphone ┆ water_access │
│ --- ┆ ---          ┆ ---    ┆ ---                ┆   ┆ ---  ┆ ---   ┆ ---       ┆ ---          │
│ str ┆ str          ┆ str    ┆ str                ┆   ┆ f64  ┆ f64   ┆ f64       ┆ f64          │
╞═════╪══════════════╪════════╪════════════════════╪═══╪══════╪═══════╪═══════════╪══════════════╡
│ SGP ┆ Singapore    ┆ Asia   ┆ South-eastern Asia ┆ … ┆ null ┆ 66.54 ┆ 145.5     ┆ 100.0        │
│ JPN ┆ Japan        ┆ Asia   ┆ Eastern Asia       ┆ … ┆ 32.9 ┆ 59.1  ┆ 96.2      ┆ 99.95242     │
│ ISL ┆ Iceland      ┆ Europe ┆ Northern Europe    ┆ … ┆ 26.1 ┆ 75.62 ┆ 107.2     ┆ 98.78217     │
│ CHE ┆ Switzerland  ┆ Europe ┆ Western Europe     ┆ … ┆ 33.1 ┆ 69.69 ┆ 123.2     ┆ 99.89987     │
│ ITA ┆ Italy        ┆ Europe ┆ Southern Europe    ┆ … ┆ 35.2 ┆ 62.45 ┆ 155.7     ┆ 99.88534     │
│ …   ┆ …            ┆ …      ┆ …                  ┆ … ┆ …    ┆ …     ┆ …         ┆ …            │
│ BFA ┆ Burkina Faso ┆ Africa ┆ Western Africa     ┆ … ┆ 47.3 ┆ 44.62 ┆ 35.3      ┆ 21.77792     │
│ GIN ┆ Guinea       ┆ Africa ┆ Western Africa     ┆ … ┆ 29.6 ┆ 48.27 ┆ 38.5      ┆ 25.27932     │
│ ZWE ┆ Zimbabwe     ┆ Africa ┆ Eastern Africa     ┆ … ┆ 50.3 ┆ 35.72 ┆ 57.6      ┆ 36.94167     │
│ TCD ┆ Chad         ┆ Africa ┆ Middle Africa      ┆ … ┆ 37.5 ┆ 45.44 ┆ 23.4      ┆ 11.82919     │
│ MOZ ┆ Mozambique   ┆ Africa ┆ Eastern Africa     ┆ … ┆ 54.0 ┆ 57.04 ┆ 31.4      ┆ 30.56033     │
└─────┴──────────────┴────────┴────────────────────┴───┴──────┴───────┴───────────┴──────────────┘

1. What country is that?

**Answer (Q1):**

2. Now, select all countries that are located in both the northern hemisphere (i.e., latitude greater than 0) and the eastern hemisphere (longitude greater than 0). Display those below

In [17]:
(
    dat
    .filter((c.lat > 0) & (c.lon > 0))
)

shape: (83, 14)
┌─────┬─────────────┬────────┬────────────────────┬───┬──────┬───────┬───────────┬──────────────┐
│ iso ┆ full_name   ┆ region ┆ subregion          ┆ … ┆ gini ┆ happy ┆ cellphone ┆ water_access │
│ --- ┆ ---         ┆ ---    ┆ ---                ┆   ┆ ---  ┆ ---   ┆ ---       ┆ ---          │
│ str ┆ str         ┆ str    ┆ str                ┆   ┆ f64  ┆ f64   ┆ f64       ┆ f64          │
╞═════╪═════════════╪════════╪════════════════════╪═══╪══════╪═══════╪═══════════╪══════════════╡
│ FIN ┆ Finland     ┆ Europe ┆ Northern Europe    ┆ … ┆ 27.7 ┆ 76.99 ┆ 156.4     ┆ 99.44798     │
│ LKA ┆ Sri Lanka   ┆ Asia   ┆ Southern Asia      ┆ … ┆ 39.3 ┆ 36.02 ┆ 83.1      ┆ 90.77437     │
│ SGP ┆ Singapore   ┆ Asia   ┆ South-eastern Asia ┆ … ┆ null ┆ 66.54 ┆ 145.5     ┆ 100.0        │
│ BGR ┆ Bulgaria    ┆ Europe ┆ Eastern Europe     ┆ … ┆ 40.3 ┆ 55.9  ┆ 137.1     ┆ 86.00395     │
│ AFG ┆ Afghanistan ┆ Asia   ┆ Southern Asia      ┆ … ┆ 27.8 ┆ 14.46 ┆ 36.1      ┆ 47.47762     │
│ …   ┆ …           ┆ …      ┆ …                  ┆ … ┆ …    ┆ …     ┆ …         ┆ …            │
│ THA ┆ Thailand    ┆ Asia   ┆ South-eastern Asia ┆ … ┆ 35.0 ┆ 62.82 ┆ 104.6     ┆ 97.79091     │
│ ALB ┆ Albania     ┆ Europe ┆ Southern Europe    ┆ … ┆ 30.8 ┆ 54.45 ┆ 91.9      ┆ 98.5473      │
│ MYS ┆ Malaysia    ┆ Asia   ┆ South-eastern Asia ┆ … ┆ 46.2 ┆ 58.68 ┆ 118.2     ┆ 95.69194     │
│ CYP ┆ Cyprus      ┆ Asia   ┆ Western Asia       ┆ … ┆ 31.2 ┆ 60.71 ┆ 123.1     ┆ 99.41781     │
│ PAK ┆ Pakistan    ┆ Asia   ┆ Southern Asia      ┆ … ┆ 29.6 ┆ 45.49 ┆ 49.8      ┆ 61.92651     │
└─────┴─────────────┴────────┴────────────────────┴───┴──────┴───────┴───────────┴──────────────┘

3. Next, select all countries that are located in either the northern hemisphere (i.e., latitude greater than 0) or the eastern hemisphere (i.e., longitude greater than 0).

In [18]:
(
    dat
    .filter((c.lat > 0) | (c.lon > 0))
)

shape: (128, 14)
┌─────┬─────────────────┬──────────┬─────────────────┬───┬──────┬───────┬───────────┬──────────────┐
│ iso ┆ full_name       ┆ region   ┆ subregion       ┆ … ┆ gini ┆ happy ┆ cellphone ┆ water_access │
│ --- ┆ ---             ┆ ---      ┆ ---             ┆   ┆ ---  ┆ ---   ┆ ---       ┆ ---          │
│ str ┆ str             ┆ str      ┆ str             ┆   ┆ f64  ┆ f64   ┆ f64       ┆ f64          │
╞═════╪═════════════════╪══════════╪═════════════════╪═══╪══════╪═══════╪═══════════╪══════════════╡
│ SEN ┆ Senegal         ┆ Africa   ┆ Western Africa  ┆ … ┆ 38.1 ┆ 50.93 ┆ 66.0      ┆ 54.93987     │
│ VEN ┆ Venezuela,      ┆ Americas ┆ South America   ┆ … ┆ 44.8 ┆ 57.65 ┆ 96.8      ┆ 95.66913     │
│     ┆ Bolivarian      ┆          ┆                 ┆   ┆      ┆       ┆           ┆              │
│     ┆ Republic…       ┆          ┆                 ┆   ┆      ┆       ┆           ┆              │
│ FIN ┆ Finland         ┆ Europe   ┆ Northern Europe ┆ … ┆ 27.7 ┆ 76.99 ┆ 156.4     ┆ 99.44798     │
│ USA ┆ United States   ┆ Americas ┆ Northern        ┆ … ┆ 47.7 ┆ 65.21 ┆ 91.7      ┆ 99.72235     │
│     ┆ of America      ┆          ┆ America         ┆   ┆      ┆       ┆           ┆              │
│ LKA ┆ Sri Lanka       ┆ Asia     ┆ Southern Asia   ┆ … ┆ 39.3 ┆ 36.02 ┆ 83.1      ┆ 90.77437     │
│ …   ┆ …               ┆ …        ┆ …               ┆ … ┆ …    ┆ …     ┆ …         ┆ …            │
│ ALB ┆ Albania         ┆ Europe   ┆ Southern Europe ┆ … ┆ 30.8 ┆ 54.45 ┆ 91.9      ┆ 98.5473      │
│ MYS ┆ Malaysia        ┆ Asia     ┆ South-eastern   ┆ … ┆ 46.2 ┆ 58.68 ┆ 118.2     ┆ 95.69194     │
│     ┆                 ┆          ┆ Asia            ┆   ┆      ┆       ┆           ┆              │
│ SLV ┆ El Salvador     ┆ Americas ┆ Central America ┆ … ┆ 38.3 ┆ 64.82 ┆ 126.9     ┆ 86.19786     │
│ CYP ┆ Cyprus          ┆ Asia     ┆ Western Asia    ┆ … ┆ 31.2 ┆ 60.71 ┆ 123.1     ┆ 99.41781     │
│ PAK ┆ Pakistan        ┆ Asia     ┆ Southern Asia   ┆ … ┆ 29.6 ┆ 45.49 ┆ 49.8      ┆ 61.92651     │
└─────┴─────────────────┴──────────┴─────────────────┴───┴──────┴───────┴───────────┴──────────────┘

3. Does this produce more or less countries than what was found in Q2?

**Answer (Q3):** More

4. Select only the countries that are in Africa.

In [20]:
(
    dat
    .filter(c.region == "Africa")
)

shape: (37, 14)
┌─────┬───────────────────┬────────┬─────────────────┬───┬──────┬───────┬───────────┬──────────────┐
│ iso ┆ full_name         ┆ region ┆ subregion       ┆ … ┆ gini ┆ happy ┆ cellphone ┆ water_access │
│ --- ┆ ---               ┆ ---    ┆ ---             ┆   ┆ ---  ┆ ---   ┆ ---       ┆ ---          │
│ str ┆ str               ┆ str    ┆ str             ┆   ┆ f64  ┆ f64   ┆ f64       ┆ f64          │
╞═════╪═══════════════════╪════════╪═════════════════╪═══╪══════╪═══════╪═══════════╪══════════════╡
│ SEN ┆ Senegal           ┆ Africa ┆ Western Africa  ┆ … ┆ 38.1 ┆ 50.93 ┆ 66.0      ┆ 54.93987     │
│ GAB ┆ Gabon             ┆ Africa ┆ Middle Africa   ┆ … ┆ 38.0 ┆ 51.04 ┆ 93.6      ┆ 49.20331     │
│ TZA ┆ Tanzania, United  ┆ Africa ┆ Eastern Africa  ┆ … ┆ 40.5 ┆ 40.42 ┆ 46.9      ┆ 26.78297     │
│     ┆ Republic of       ┆        ┆                 ┆   ┆      ┆       ┆           ┆              │
│ MWI ┆ Malawi            ┆ Africa ┆ Eastern Africa  ┆ … ┆ 38.5 ┆ 32.72 ┆ 21.0      ┆ 38.45707     │
│ GHA ┆ Ghana             ┆ Africa ┆ Western Africa  ┆ … ┆ 43.5 ┆ 42.98 ┆ 68.4      ┆ 22.67011     │
│ …   ┆ …                 ┆ …      ┆ …               ┆ … ┆ …    ┆ …     ┆ …         ┆ …            │
│ ETH ┆ Ethiopia          ┆ Africa ┆ Eastern Africa  ┆ … ┆ 35.0 ┆ 40.93 ┆ 7.6       ┆ 8.04716      │
│ CMR ┆ Cameroon          ┆ Africa ┆ Middle Africa   ┆ … ┆ 46.6 ┆ 49.46 ┆ 43.9      ┆ 41.90133     │
│ LBR ┆ Liberia           ┆ Africa ┆ Western Africa  ┆ … ┆ 35.3 ┆ 44.94 ┆ 38.7      ┆ 19.63094     │
│ MAR ┆ Morocco           ┆ Africa ┆ Northern Africa ┆ … ┆ 39.5 ┆ 44.87 ┆ 98.5      ┆ 84.47591     │
│ GMB ┆ Gambia            ┆ Africa ┆ Western Africa  ┆ … ┆ null ┆ 46.91 ┆ 76.7      ┆ 46.90722     │
└─────┴───────────────────┴────────┴─────────────────┴───┴──────┴───────┴───────────┴──────────────┘

5. Now, select countries that are in either Africa or Europe without using the `|` (or) operator.

In [21]:
(
    dat
    .filter((c.region == "Africa") | (c.region == "Europe"))
)

shape: (75, 14)
┌─────┬───────────────────┬────────┬─────────────────┬───┬──────┬───────┬───────────┬──────────────┐
│ iso ┆ full_name         ┆ region ┆ subregion       ┆ … ┆ gini ┆ happy ┆ cellphone ┆ water_access │
│ --- ┆ ---               ┆ ---    ┆ ---             ┆   ┆ ---  ┆ ---   ┆ ---       ┆ ---          │
│ str ┆ str               ┆ str    ┆ str             ┆   ┆ f64  ┆ f64   ┆ f64       ┆ f64          │
╞═════╪═══════════════════╪════════╪═════════════════╪═══╪══════╪═══════╪═══════════╪══════════════╡
│ SEN ┆ Senegal           ┆ Africa ┆ Western Africa  ┆ … ┆ 38.1 ┆ 50.93 ┆ 66.0      ┆ 54.93987     │
│ FIN ┆ Finland           ┆ Europe ┆ Northern Europe ┆ … ┆ 27.7 ┆ 76.99 ┆ 156.4     ┆ 99.44798     │
│ GAB ┆ Gabon             ┆ Africa ┆ Middle Africa   ┆ … ┆ 38.0 ┆ 51.04 ┆ 93.6      ┆ 49.20331     │
│ BGR ┆ Bulgaria          ┆ Europe ┆ Eastern Europe  ┆ … ┆ 40.3 ┆ 55.9  ┆ 137.1     ┆ 86.00395     │
│ TZA ┆ Tanzania, United  ┆ Africa ┆ Eastern Africa  ┆ … ┆ 40.5 ┆ 40.42 ┆ 46.9      ┆ 26.78297     │
│     ┆ Republic of       ┆        ┆                 ┆   ┆      ┆       ┆           ┆              │
│ …   ┆ …                 ┆ …      ┆ …               ┆ … ┆ …    ┆ …     ┆ …         ┆ …            │
│ LUX ┆ Luxembourg        ┆ Europe ┆ Western Europe  ┆ … ┆ 34.9 ┆ 70.16 ┆ 143.3     ┆ 97.60054     │
│ LTU ┆ Lithuania         ┆ Europe ┆ Northern Europe ┆ … ┆ 35.3 ┆ 65.53 ┆ 157.9     ┆ 92.73568     │
│ MNE ┆ Montenegro        ┆ Europe ┆ Southern Europe ┆ … ┆ 29.4 ┆ 58.13 ┆ 185.1     ┆ 96.657       │
│ GMB ┆ Gambia            ┆ Africa ┆ Western Africa  ┆ … ┆ null ┆ 46.91 ┆ 76.7      ┆ 46.90722     │
│ ALB ┆ Albania           ┆ Europe ┆ Southern Europe ┆ … ┆ 30.8 ┆ 54.45 ┆ 91.9      ┆ 98.5473      │
└─────┴───────────────────┴────────┴─────────────────┴───┴──────┴───────┴───────────┴──────────────┘

6. The population column in our dataset is again given in millions (i.e., 5.265 is 5265000). Create a new column called `raw_pop` that contains the raw population (i.e., the 5265000 as an example should be what you calculate).

In [8]:
(
    dat
    .with_columns(raw_pop = c.pop * 10000000)
)

shape: (135, 15)
┌─────┬───────────────┬──────────┬───────────────┬───┬───────┬───────────┬──────────────┬──────────┐
│ iso ┆ full_name     ┆ region   ┆ subregion     ┆ … ┆ happy ┆ cellphone ┆ water_access ┆ raw_pop  │
│ --- ┆ ---           ┆ ---      ┆ ---           ┆   ┆ ---   ┆ ---       ┆ ---          ┆ ---      │
│ str ┆ str           ┆ str      ┆ str           ┆   ┆ f64   ┆ f64       ┆ f64          ┆ f64      │
╞═════╪═══════════════╪══════════╪═══════════════╪═══╪═══════╪═══════════╪══════════════╪══════════╡
│ SEN ┆ Senegal       ┆ Africa   ┆ Western       ┆ … ┆ 50.93 ┆ 66.0      ┆ 54.93987     ┆ 1.8932e8 │
│     ┆               ┆          ┆ Africa        ┆   ┆       ┆           ┆              ┆          │
│ VEN ┆ Venezuela,    ┆ Americas ┆ South America ┆ … ┆ 57.65 ┆ 96.8      ┆ 95.66913     ┆ 2.8517e8 │
│     ┆ Bolivarian    ┆          ┆               ┆   ┆       ┆           ┆              ┆          │
│     ┆ Republic…     ┆          ┆               ┆   ┆       ┆           ┆              ┆          │
│ FIN ┆ Finland       ┆ Europe   ┆ Northern      ┆ … ┆ 76.99 ┆ 156.4     ┆ 99.44798     ┆ 5.623e7  │
│     ┆               ┆          ┆ Europe        ┆   ┆       ┆           ┆              ┆          │
│ USA ┆ United States ┆ Americas ┆ Northern      ┆ … ┆ 65.21 ┆ 91.7      ┆ 99.72235     ┆ 3.4728e9 │
│     ┆ of America    ┆          ┆ America       ┆   ┆       ┆           ┆              ┆          │
│ LKA ┆ Sri Lanka     ┆ Asia     ┆ Southern Asia ┆ … ┆ 36.02 ┆ 83.1      ┆ 90.77437     ┆ 2.3229e8 │
│ …   ┆ …             ┆ …        ┆ …             ┆ … ┆ …     ┆ …         ┆ …            ┆ …        │
│ ALB ┆ Albania       ┆ Europe   ┆ Southern      ┆ … ┆ 54.45 ┆ 91.9      ┆ 98.5473      ┆ 2.7720e7 │
│     ┆               ┆          ┆ Europe        ┆   ┆       ┆           ┆              ┆          │
│ MYS ┆ Malaysia      ┆ Asia     ┆ South-eastern ┆ … ┆ 58.68 ┆ 118.2     ┆ 95.69194     ┆ 3.5978e8 │
│     ┆               ┆          ┆ Asia          ┆   ┆       ┆           ┆              ┆          │
│ SLV ┆ El Salvador   ┆ Americas ┆ Central       ┆ … ┆ 64.82 ┆ 126.9     ┆ 86.19786     ┆ 6.366e7  │
│     ┆               ┆          ┆ America       ┆   ┆       ┆           ┆              ┆          │
│ CYP ┆ Cyprus        ┆ Asia     ┆ Western Asia  ┆ … ┆ 60.71 ┆ 123.1     ┆ 99.41781     ┆ 1.371e7  │
│ PAK ┆ Pakistan      ┆ Asia     ┆ Southern Asia ┆ … ┆ 45.49 ┆ 49.8      ┆ 61.92651     ┆ 2.5522e9 │
└─────┴───────────────┴──────────┴───────────────┴───┴───────┴───────────┴──────────────┴──────────┘

7. The GDP per capita of the US (according to this dataset) is 78389. Compute the distance (i.e., difference score) of all other countries GDP to the United States, making sure to take the absolute value to not have negatives (`.abs`). This is called the **absolute distance.**

In [11]:
(
    dat
    .with_columns(gdp_diff = (c.gdp - 78389).abs())
)

shape: (135, 15)
┌─────┬───────────────┬──────────┬───────────────┬───┬───────┬───────────┬──────────────┬──────────┐
│ iso ┆ full_name     ┆ region   ┆ subregion     ┆ … ┆ happy ┆ cellphone ┆ water_access ┆ gdp_diff │
│ --- ┆ ---           ┆ ---      ┆ ---           ┆   ┆ ---   ┆ ---       ┆ ---          ┆ ---      │
│ str ┆ str           ┆ str      ┆ str           ┆   ┆ f64   ┆ f64       ┆ f64          ┆ i64      │
╞═════╪═══════════════╪══════════╪═══════════════╪═══╪═══════╪═══════════╪══════════════╪══════════╡
│ SEN ┆ Senegal       ┆ Africa   ┆ Western       ┆ … ┆ 50.93 ┆ 66.0      ┆ 54.93987     ┆ 73518    │
│     ┆               ┆          ┆ Africa        ┆   ┆       ┆           ┆              ┆          │
│ VEN ┆ Venezuela,    ┆ Americas ┆ South America ┆ … ┆ 57.65 ┆ 96.8      ┆ 95.66913     ┆ 69490    │
│     ┆ Bolivarian    ┆          ┆               ┆   ┆       ┆           ┆              ┆          │
│     ┆ Republic…     ┆          ┆               ┆   ┆       ┆           ┆              ┆          │
│ FIN ┆ Finland       ┆ Europe   ┆ Northern      ┆ … ┆ 76.99 ┆ 156.4     ┆ 99.44798     ┆ 20815    │
│     ┆               ┆          ┆ Europe        ┆   ┆       ┆           ┆              ┆          │
│ USA ┆ United States ┆ Americas ┆ Northern      ┆ … ┆ 65.21 ┆ 91.7      ┆ 99.72235     ┆ 0        │
│     ┆ of America    ┆          ┆ America       ┆   ┆       ┆           ┆              ┆          │
│ LKA ┆ Sri Lanka     ┆ Asia     ┆ Southern Asia ┆ … ┆ 36.02 ┆ 83.1      ┆ 90.77437     ┆ 64009    │
│ …   ┆ …             ┆ …        ┆ …             ┆ … ┆ …     ┆ …         ┆ …            ┆ …        │
│ ALB ┆ Albania       ┆ Europe   ┆ Southern      ┆ … ┆ 54.45 ┆ 91.9      ┆ 98.5473      ┆ 58027    │
│     ┆               ┆          ┆ Europe        ┆   ┆       ┆           ┆              ┆          │
│ MYS ┆ Malaysia      ┆ Asia     ┆ South-eastern ┆ … ┆ 58.68 ┆ 118.2     ┆ 95.69194     ┆ 42399    │
│     ┆               ┆          ┆ Asia          ┆   ┆       ┆           ┆              ┆          │
│ SLV ┆ El Salvador   ┆ Americas ┆ Central       ┆ … ┆ 64.82 ┆ 126.9     ┆ 86.19786     ┆ 66168    │
│     ┆               ┆          ┆ America       ┆   ┆       ┆           ┆              ┆          │
│ CYP ┆ Cyprus        ┆ Asia     ┆ Western Asia  ┆ … ┆ 60.71 ┆ 123.1     ┆ 99.41781     ┆ 22669    │
│ PAK ┆ Pakistan      ┆ Asia     ┆ Southern Asia ┆ … ┆ 45.49 ┆ 49.8      ┆ 61.92651     ┆ 72672    │
└─────┴───────────────┴──────────┴───────────────┴───┴───────┴───────────┴──────────────┴──────────┘

8. Find the country **in each region** that has the closest GDP per capita to the United States. Note: You will probably want to first copy your answer above and make changes rather than starting from scratch.

In [12]:
(
    dat
    .with_columns(gdp_diff = (c.gdp - 78389).abs())
    .sort(c.gdp_diff)
    .group_by(c.region)
    .head(1)
)

shape: (5, 15)
┌──────────┬─────┬───────────────┬───────────────┬───┬───────┬───────────┬──────────────┬──────────┐
│ region   ┆ iso ┆ full_name     ┆ subregion     ┆ … ┆ happy ┆ cellphone ┆ water_access ┆ gdp_diff │
│ ---      ┆ --- ┆ ---           ┆ ---           ┆   ┆ ---   ┆ ---       ┆ ---          ┆ ---      │
│ str      ┆ str ┆ str           ┆ str           ┆   ┆ f64   ┆ f64       ┆ f64          ┆ i64      │
╞══════════╪═════╪═══════════════╪═══════════════╪═══╪═══════╪═══════════╪══════════════╪══════════╡
│ Americas ┆ USA ┆ United States ┆ Northern      ┆ … ┆ 65.21 ┆ 91.7      ┆ 99.72235     ┆ 0        │
│          ┆     ┆ of America    ┆ America       ┆   ┆       ┆           ┆              ┆          │
│ Africa   ┆ MUS ┆ Mauritius     ┆ Eastern       ┆ … ┆ 57.59 ┆ 92.8      ┆ 95.45876     ┆ 49462    │
│          ┆     ┆               ┆ Africa        ┆   ┆       ┆           ┆              ┆          │
│ Oceania  ┆ AUS ┆ Australia     ┆ Australia and ┆ … ┆ 70.25 ┆ 101.6     ┆ 99.99923     ┆ 16446    │
│          ┆     ┆               ┆ New Zealand   ┆   ┆       ┆           ┆              ┆          │
│ Asia     ┆ ARE ┆ United Arab   ┆ Western Asia  ┆ … ┆ 67.28 ┆ 157.5     ┆ 99.10363     ┆ 5729     │
│          ┆     ┆ Emirates      ┆               ┆   ┆       ┆           ┆              ┆          │
│ Europe   ┆ DNK ┆ Denmark       ┆ Northern      ┆ … ┆ 75.04 ┆ 115.7     ┆ 99.59723     ┆ 1052     │
│          ┆     ┆               ┆ Europe        ┆   ┆       ┆           ┆              ┆          │
└──────────┴─────┴───────────────┴───────────────┴───┴───────┴───────────┴──────────────┴──────────┘

9. The United States is, of course, the closest to itself in "Americas". So finally modify the previous code to remove the United States from the data so that we can see what other country it is closest to in its own region. Note: When we say "modify" in these notes, that means to copy and then modify; don't change the original code itself.

In [16]:
(
    dat
    .with_columns(gdp_diff = (c.gdp - 78389).abs())
    .sort((c.gdp_diff) & (c.iso != "USA"))
    .group_by(c.region)
    .head(1)
)

shape: (5, 15)
┌──────────┬─────┬───────────────┬───────────────┬───┬───────┬───────────┬──────────────┬──────────┐
│ region   ┆ iso ┆ full_name     ┆ subregion     ┆ … ┆ happy ┆ cellphone ┆ water_access ┆ gdp_diff │
│ ---      ┆ --- ┆ ---           ┆ ---           ┆   ┆ ---   ┆ ---       ┆ ---          ┆ ---      │
│ str      ┆ str ┆ str           ┆ str           ┆   ┆ f64   ┆ f64       ┆ f64          ┆ i64      │
╞══════════╪═════╪═══════════════╪═══════════════╪═══╪═══════╪═══════════╪══════════════╪══════════╡
│ Europe   ┆ BGR ┆ Bulgaria      ┆ Eastern       ┆ … ┆ 55.9  ┆ 137.1     ┆ 86.00395     ┆ 42178    │
│          ┆     ┆               ┆ Europe        ┆   ┆       ┆           ┆              ┆          │
│ Oceania  ┆ AUS ┆ Australia     ┆ Australia and ┆ … ┆ 70.25 ┆ 101.6     ┆ 99.99923     ┆ 16446    │
│          ┆     ┆               ┆ New Zealand   ┆   ┆       ┆           ┆              ┆          │
│ Africa   ┆ SEN ┆ Senegal       ┆ Western       ┆ … ┆ 50.93 ┆ 66.0      ┆ 54.93987     ┆ 73518    │
│          ┆     ┆               ┆ Africa        ┆   ┆       ┆           ┆              ┆          │
│ Americas ┆ VEN ┆ Venezuela,    ┆ South America ┆ … ┆ 57.65 ┆ 96.8      ┆ 95.66913     ┆ 69490    │
│          ┆     ┆ Bolivarian    ┆               ┆   ┆       ┆           ┆              ┆          │
│          ┆     ┆ Republic…     ┆               ┆   ┆       ┆           ┆              ┆          │
│ Asia     ┆ AFG ┆ Afghanistan   ┆ Southern Asia ┆ … ┆ 14.46 ┆ 36.1      ┆ 47.47762     ┆ 76296    │
└──────────┴─────┴───────────────┴───────────────┴───┴───────┴───────────┴──────────────┴──────────┘