<a href="https://colab.research.google.com/github/tettehdaniel/python-labs/blob/main/Notebooks/Notebook06_Review1_5_SV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 06 — Exam 1 Review

**Main Objective**

- Review the following Data Manipulation Techniques

    1. Sorting
    2. Filtering
    3. Grouping
    4. Variable Creation
    5. Summarizing/Aggregating
    6. Piping

## Setup

Please run the setup code below

In [1]:
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py

from funs import *

In [2]:
import numpy as np
import polars as pl

from plotnine import *
from polars import col as c
theme_set(theme_minimal())

path = "https://raw.githubusercontent.com/ajcollins16/DSST289_Fall2026_AJC/refs/heads/main/"

In [3]:
dat = pl.read_csv(path + "Data/metro.csv")

In [4]:
dat

shape: (934, 13)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name        ┆ geoid ┆ quad ┆ lon         ┆ … ┆ percent_ow ┆ rent_1br_m ┆ rent_perc_ ┆ division   │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ n          ┆ edian      ┆ income     ┆ ---        │
│ str         ┆ i64   ┆ str  ┆ f64         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str        │
│             ┆       ┆      ┆             ┆   ┆ f64        ┆ i64        ┆ f64        ┆            │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ New York    ┆ 35620 ┆ NE   ┆ -74.101056  ┆ … ┆ 55.3       ┆ 1430       ┆ 31.0       ┆ Middle     │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Los Angeles ┆ 31080 ┆ W    ┆ -118.148722 ┆ … ┆ 51.3       ┆ 1468       ┆ 33.6       ┆ Pacific    │
│ Chicago     ┆ 16980 ┆ NC   ┆ -87.95882   ┆ … ┆ 68.9       ┆ 1060       ┆ 29.0       ┆ East North │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Dallas      ┆ 19100 ┆ S    ┆ -96.970508  ┆ … ┆ 64.1       ┆ 1106       ┆ 29.1       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Houston     ┆ 26420 ┆ S    ┆ -95.401574  ┆ … ┆ 65.1       ┆ 997        ┆ 30.0       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zapata      ┆ 49820 ┆ S    ┆ -99.168533  ┆ … ┆ 77.1       ┆ 321        ┆ 34.6       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Ketchikan   ┆ 28540 ┆ O    ┆ -130.927217 ┆ … ┆ 67.5       ┆ 946        ┆ 31.2       ┆ Pacific    │
│ Craig       ┆ 18780 ┆ W    ┆ -108.207523 ┆ … ┆ 72.8       ┆ 485        ┆ 29.0       ┆ Mountain   │
│ Vernon      ┆ 46900 ┆ S    ┆ -99.240853  ┆ … ┆ 62.0       ┆ 503        ┆ 22.0       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Lamesa      ┆ 29500 ┆ S    ┆ -101.947637 ┆ … ┆ 71.5       ┆ 611        ┆ 34.5       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

## Review Day

This notebook is a review of the data manipulation techniques we have learned so far. We will work with the `metro` dataset, which contains information about US metropolitan areas from the [American Community Survey](https://www.census.gov/programs-surveys/acs/about.html), which is just a yearly (optional) census to assess various community and state factors. The datset includes variables such as population (in millions), population density, median age, median household income, home ownership rates, median rent for a one-bedroom apartment, and geographic information including which census division each metro area belongs to.

### Questions

1. Sort the metropolitan areas by population, with the largest metros at the top

In [6]:
(
    dat
    .sort(c.pop, descending=True)
)

shape: (934, 13)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name        ┆ geoid ┆ quad ┆ lon         ┆ … ┆ percent_ow ┆ rent_1br_m ┆ rent_perc_ ┆ division   │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ n          ┆ edian      ┆ income     ┆ ---        │
│ str         ┆ i64   ┆ str  ┆ f64         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str        │
│             ┆       ┆      ┆             ┆   ┆ f64        ┆ i64        ┆ f64        ┆            │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ New York    ┆ 35620 ┆ NE   ┆ -74.101056  ┆ … ┆ 55.3       ┆ 1430       ┆ 31.0       ┆ Middle     │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Los Angeles ┆ 31080 ┆ W    ┆ -118.148722 ┆ … ┆ 51.3       ┆ 1468       ┆ 33.6       ┆ Pacific    │
│ Chicago     ┆ 16980 ┆ NC   ┆ -87.95882   ┆ … ┆ 68.9       ┆ 1060       ┆ 29.0       ┆ East North │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Dallas      ┆ 19100 ┆ S    ┆ -96.970508  ┆ … ┆ 64.1       ┆ 1106       ┆ 29.1       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Houston     ┆ 26420 ┆ S    ┆ -95.401574  ┆ … ┆ 65.1       ┆ 997        ┆ 30.0       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zapata      ┆ 49820 ┆ S    ┆ -99.168533  ┆ … ┆ 77.1       ┆ 321        ┆ 34.6       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Ketchikan   ┆ 28540 ┆ O    ┆ -130.927217 ┆ … ┆ 67.5       ┆ 946        ┆ 31.2       ┆ Pacific    │
│ Craig       ┆ 18780 ┆ W    ┆ -108.207523 ┆ … ┆ 72.8       ┆ 485        ┆ 29.0       ┆ Mountain   │
│ Vernon      ┆ 46900 ┆ S    ┆ -99.240853  ┆ … ┆ 62.0       ┆ 503        ┆ 22.0       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Lamesa      ┆ 29500 ┆ S    ┆ -101.947637 ┆ … ┆ 71.5       ┆ 611        ┆ 34.5       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

2. Find the metro area with the highest median household income.

In [7]:
(
    dat
    .sort(c.hh_income_median, descending = True)
)

shape: (934, 13)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name        ┆ geoid ┆ quad ┆ lon         ┆ … ┆ percent_ow ┆ rent_1br_m ┆ rent_perc_ ┆ division   │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ n          ┆ edian      ┆ income     ┆ ---        │
│ str         ┆ i64   ┆ str  ┆ f64         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str        │
│             ┆       ┆      ┆             ┆   ┆ f64        ┆ i64        ┆ f64        ┆            │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ San Jose    ┆ 41940 ┆ W    ┆ -121.372676 ┆ … ┆ 58.5       ┆ 2227       ┆ 27.8       ┆ Pacific    │
│ Los Alamos  ┆ 31060 ┆ W    ┆ -106.307297 ┆ … ┆ 79.0       ┆ 843        ┆ 18.0       ┆ Mountain   │
│ San         ┆ 41860 ┆ W    ┆ -122.166182 ┆ … ┆ 58.4       ┆ 1940       ┆ 28.3       ┆ Pacific    │
│ Francisco   ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆            │
│ Washington  ┆ 47900 ┆ S    ┆ -77.513075  ┆ … ┆ 67.4       ┆ 1601       ┆ 28.8       ┆ South      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Heber       ┆ 25720 ┆ W    ┆ -111.039097 ┆ … ┆ 77.7       ┆ 1240       ┆ 27.2       ┆ Mountain   │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Aguadilla   ┆ 10380 ┆ O    ┆ -66.95338   ┆ … ┆ 67.1       ┆ 265        ┆ 29.9       ┆ South      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ San Germán  ┆ 41900 ┆ O    ┆ -67.061823  ┆ … ┆ 72.0       ┆ 239        ┆ 31.1       ┆ South      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Guayama     ┆ 25020 ┆ O    ┆ -66.083671  ┆ … ┆ 71.6       ┆ 196        ┆ 30.5       ┆ South      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Yauco       ┆ 49500 ┆ O    ┆ -66.824074  ┆ … ┆ 72.1       ┆ 261        ┆ 29.2       ┆ South      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Mayagüez    ┆ 32420 ┆ O    ┆ -67.192743  ┆ … ┆ 60.3       ┆ 229        ┆ 36.6       ┆ South      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

3. Sort the data by median age, with the youngest metros first.

In [8]:
(
    dat
    .sort(c.age_median)
)

shape: (934, 13)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name        ┆ geoid ┆ quad ┆ lon         ┆ … ┆ percent_ow ┆ rent_1br_m ┆ rent_perc_ ┆ division   │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ n          ┆ edian      ┆ income     ┆ ---        │
│ str         ┆ i64   ┆ str  ┆ f64         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str        │
│             ┆       ┆      ┆             ┆   ┆ f64        ┆ i64        ┆ f64        ┆            │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Rexburg     ┆ 39940 ┆ W    ┆ -111.518023 ┆ … ┆ 60.4       ┆ 743        ┆ 35.2       ┆ Mountain   │
│ Jacksonvill ┆ 27340 ┆ S    ┆ -77.432055  ┆ … ┆ 57.3       ┆ 646        ┆ 29.6       ┆ South      │
│ e           ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Fort        ┆ 22780 ┆ NC   ┆ -92.20759   ┆ … ┆ 56.2       ┆ 500        ┆ 22.8       ┆ West North │
│ Leonard     ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Wood        ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆            │
│ Laramie     ┆ 29660 ┆ W    ┆ -105.724306 ┆ … ┆ 54.9       ┆ 681        ┆ 35.1       ┆ Mountain   │
│ Pullman     ┆ 39420 ┆ W    ┆ -117.523085 ┆ … ┆ 51.4       ┆ 692        ┆ 40.9       ┆ Pacific    │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Rockport    ┆ 40530 ┆ S    ┆ -96.993507  ┆ … ┆ 79.0       ┆ 737        ┆ 27.7       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Torrington  ┆ 45860 ┆ NE   ┆ -73.245421  ┆ … ┆ 80.3       ┆ 948        ┆ 29.6       ┆ New        │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ England    │
│ Barnstable  ┆ 12700 ┆ NE   ┆ -70.290799  ┆ … ┆ 82.0       ┆ 926        ┆ 33.3       ┆ New        │
│ Town        ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ England    │
│ Punta Gorda ┆ 39460 ┆ S    ┆ -81.912254  ┆ … ┆ 82.3       ┆ 853        ┆ 34.8       ┆ South      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Vineyard    ┆ 47240 ┆ NE   ┆ -70.650085  ┆ … ┆ 75.7       ┆ 1090       ┆ 30.6       ┆ New        │
│ Haven       ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ England    │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

3. What places have the youngest population (list the top three)?

**Answer (Q3):** Rexburg, Jacksonville, Fort Leonard Wood

4. Select only the metro areas located in the South (where the `quad` column equals "S").

In [9]:
(
    dat
    .filter(c.quad == "S")
)

shape: (377, 13)
┌────────────┬───────┬──────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ name       ┆ geoid ┆ quad ┆ lon         ┆ … ┆ percent_own ┆ rent_1br_m ┆ rent_perc_ ┆ division   │
│ ---        ┆ ---   ┆ ---  ┆ ---         ┆   ┆ ---         ┆ edian      ┆ income     ┆ ---        │
│ str        ┆ i64   ┆ str  ┆ f64         ┆   ┆ f64         ┆ ---        ┆ ---        ┆ str        │
│            ┆       ┆      ┆             ┆   ┆             ┆ i64        ┆ f64        ┆            │
╞════════════╪═══════╪══════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ Dallas     ┆ 19100 ┆ S    ┆ -96.970508  ┆ … ┆ 64.1        ┆ 1106       ┆ 29.1       ┆ West South │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Central    │
│ Houston    ┆ 26420 ┆ S    ┆ -95.401574  ┆ … ┆ 65.1        ┆ 997        ┆ 30.0       ┆ West South │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Central    │
│ Washington ┆ 47900 ┆ S    ┆ -77.513075  ┆ … ┆ 67.4        ┆ 1601       ┆ 28.8       ┆ South      │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Atlantic   │
│ Miami      ┆ 33100 ┆ S    ┆ -80.506307  ┆ … ┆ 60.8        ┆ 1230       ┆ 36.8       ┆ South      │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Atlantic   │
│ Atlanta    ┆ 12060 ┆ S    ┆ -84.399567  ┆ … ┆ 67.3        ┆ 1181       ┆ 30.3       ┆ South      │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Atlantic   │
│ …          ┆ …     ┆ …    ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ Sweetwater ┆ 45020 ┆ S    ┆ -100.405986 ┆ … ┆ 62.6        ┆ 577        ┆ 24.8       ┆ West South │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Central    │
│ Pecos      ┆ 37780 ┆ S    ┆ -103.669712 ┆ … ┆ 74.7        ┆ 818        ┆ 27.4       ┆ West South │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Central    │
│ Zapata     ┆ 49820 ┆ S    ┆ -99.168533  ┆ … ┆ 77.1        ┆ 321        ┆ 34.6       ┆ West South │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Central    │
│ Vernon     ┆ 46900 ┆ S    ┆ -99.240853  ┆ … ┆ 62.0        ┆ 503        ┆ 22.0       ┆ West South │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Central    │
│ Lamesa     ┆ 29500 ┆ S    ┆ -101.947637 ┆ … ┆ 71.5        ┆ 611        ┆ 34.5       ┆ West South │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Central    │
└────────────┴───────┴──────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

5. Select the metros that have a population density greater than 500 people per square mile.

In [10]:
(
    dat
    .filter(c.density > 500)
)

shape: (11, 13)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name        ┆ geoid ┆ quad ┆ lon         ┆ … ┆ percent_ow ┆ rent_1br_m ┆ rent_perc_ ┆ division   │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ n          ┆ edian      ┆ income     ┆ ---        │
│ str         ┆ i64   ┆ str  ┆ f64         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str        │
│             ┆       ┆      ┆             ┆   ┆ f64        ┆ i64        ┆ f64        ┆            │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ New York    ┆ 35620 ┆ NE   ┆ -74.101056  ┆ … ┆ 55.3       ┆ 1430       ┆ 31.0       ┆ Middle     │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Los Angeles ┆ 31080 ┆ W    ┆ -118.148722 ┆ … ┆ 51.3       ┆ 1468       ┆ 33.6       ┆ Pacific    │
│ Chicago     ┆ 16980 ┆ NC   ┆ -87.95882   ┆ … ┆ 68.9       ┆ 1060       ┆ 29.0       ┆ East North │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Philadelphi ┆ 37980 ┆ NE   ┆ -75.302635  ┆ … ┆ 71.1       ┆ 1083       ┆ 30.0       ┆ Middle     │
│ a           ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Boston      ┆ 14460 ┆ NE   ┆ -71.099912  ┆ … ┆ 66.4       ┆ 1390       ┆ 29.5       ┆ New        │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ England    │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ San Juan    ┆ 41980 ┆ O    ┆ -66.112516  ┆ … ┆ 69.3       ┆ 379        ┆ 31.9       ┆ South      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Urban       ┆ 46520 ┆ O    ┆ -158.092955 ┆ … ┆ 61.4       ┆ 1399       ┆ 33.4       ┆ Pacific    │
│ Honolulu    ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆            │
│ Bridgeport  ┆ 14860 ┆ NE   ┆ -73.389374  ┆ … ┆ 69.3       ┆ 1329       ┆ 32.2       ┆ New        │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ England    │
│ New Haven   ┆ 35300 ┆ NE   ┆ -72.931983  ┆ … ┆ 66.0       ┆ 1040       ┆ 30.7       ┆ New        │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ England    │
│ Trenton     ┆ 45940 ┆ NE   ┆ -74.701703  ┆ … ┆ 65.7       ┆ 1126       ┆ 30.2       ┆ Middle     │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

6. Find the metros where residents spend more than 30 percent of their income on rent.

In [11]:
(
    dat
    .filter(c.rent_perc_income > 30)
)

shape: (256, 13)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name        ┆ geoid ┆ quad ┆ lon         ┆ … ┆ percent_ow ┆ rent_1br_m ┆ rent_perc_ ┆ division   │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ n          ┆ edian      ┆ income     ┆ ---        │
│ str         ┆ i64   ┆ str  ┆ f64         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str        │
│             ┆       ┆      ┆             ┆   ┆ f64        ┆ i64        ┆ f64        ┆            │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ New York    ┆ 35620 ┆ NE   ┆ -74.101056  ┆ … ┆ 55.3       ┆ 1430       ┆ 31.0       ┆ Middle     │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Los Angeles ┆ 31080 ┆ W    ┆ -118.148722 ┆ … ┆ 51.3       ┆ 1468       ┆ 33.6       ┆ Pacific    │
│ Miami       ┆ 33100 ┆ S    ┆ -80.506307  ┆ … ┆ 60.8       ┆ 1230       ┆ 36.8       ┆ South      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Atlanta     ┆ 12060 ┆ S    ┆ -84.399567  ┆ … ┆ 67.3       ┆ 1181       ┆ 30.3       ┆ South      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ Riverside   ┆ 40140 ┆ W    ┆ -116.127488 ┆ … ┆ 65.2       ┆ 1120       ┆ 34.0       ┆ Pacific    │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Helena      ┆ 25760 ┆ S    ┆ -90.849045  ┆ … ┆ 50.4       ┆ 406        ┆ 33.5       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Fairfield   ┆ 21840 ┆ NC   ┆ -91.948906  ┆ … ┆ 66.3       ┆ 498        ┆ 32.0       ┆ West North │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Zapata      ┆ 49820 ┆ S    ┆ -99.168533  ┆ … ┆ 77.1       ┆ 321        ┆ 34.6       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ Ketchikan   ┆ 28540 ┆ O    ┆ -130.927217 ┆ … ┆ 67.5       ┆ 946        ┆ 31.2       ┆ Pacific    │
│ Lamesa      ┆ 29500 ┆ S    ┆ -101.947637 ┆ … ┆ 71.5       ┆ 611        ┆ 34.5       ┆ West South │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ Central    │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

7. Select the metros that are in either the Pacific or New England division

In [33]:
(
    dat
    .filter((c.division == "Pacific") | (c.division == "New England"))
)

shape: (108, 13)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name        ┆ geoid ┆ quad ┆ lon         ┆ … ┆ percent_ow ┆ rent_1br_m ┆ rent_perc_ ┆ division   │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ n          ┆ edian      ┆ income     ┆ ---        │
│ str         ┆ i64   ┆ str  ┆ f64         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str        │
│             ┆       ┆      ┆             ┆   ┆ f64        ┆ i64        ┆ f64        ┆            │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Los Angeles ┆ 31080 ┆ W    ┆ -118.148722 ┆ … ┆ 51.3       ┆ 1468       ┆ 33.6       ┆ Pacific    │
│ Boston      ┆ 14460 ┆ NE   ┆ -71.099912  ┆ … ┆ 66.4       ┆ 1390       ┆ 29.5       ┆ New        │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ England    │
│ San         ┆ 41860 ┆ W    ┆ -122.166182 ┆ … ┆ 58.4       ┆ 1940       ┆ 28.3       ┆ Pacific    │
│ Francisco   ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆            │
│ Riverside   ┆ 40140 ┆ W    ┆ -116.127488 ┆ … ┆ 65.2       ┆ 1120       ┆ 34.0       ┆ Pacific    │
│ Seattle     ┆ 42660 ┆ W    ┆ -121.853072 ┆ … ┆ 64.7       ┆ 1478       ┆ 29.1       ┆ Pacific    │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Hood River  ┆ 26220 ┆ W    ┆ -121.650975 ┆ … ┆ 72.1       ┆ 670        ┆ 26.3       ┆ Pacific    │
│ Brookings   ┆ 15060 ┆ W    ┆ -124.156281 ┆ … ┆ 76.3       ┆ 782        ┆ 27.7       ┆ Pacific    │
│ Othello     ┆ 36830 ┆ W    ┆ -118.561139 ┆ … ┆ 60.5       ┆ 602        ┆ 25.2       ┆ Pacific    │
│ Vineyard    ┆ 47240 ┆ NE   ┆ -70.650085  ┆ … ┆ 75.7       ┆ 1090       ┆ 30.6       ┆ New        │
│ Haven       ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ England    │
│ Ketchikan   ┆ 28540 ┆ O    ┆ -130.927217 ┆ … ┆ 67.5       ┆ 946        ┆ 31.2       ┆ Pacific    │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

8. Find metros in the South that have a median household income above $80,000. Use two separate filter steps.

In [25]:
(
    dat
    .filter(c.quad == "S")
    .filter(c.hh_income_median > 80000)
)

shape: (7, 13)
┌────────────┬───────┬──────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ name       ┆ geoid ┆ quad ┆ lon         ┆ … ┆ percent_own ┆ rent_1br_m ┆ rent_perc_ ┆ division   │
│ ---        ┆ ---   ┆ ---  ┆ ---         ┆   ┆ ---         ┆ edian      ┆ income     ┆ ---        │
│ str        ┆ i64   ┆ str  ┆ f64         ┆   ┆ f64         ┆ ---        ┆ ---        ┆ str        │
│            ┆       ┆      ┆             ┆   ┆             ┆ i64        ┆ f64        ┆            │
╞════════════╪═══════╪══════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ Washington ┆ 47900 ┆ S    ┆ -77.513075  ┆ … ┆ 67.4        ┆ 1601       ┆ 28.8       ┆ South      │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Atlantic   │
│ Baltimore  ┆ 12580 ┆ S    ┆ -76.579833  ┆ … ┆ 70.6        ┆ 1132       ┆ 30.0       ┆ South      │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Atlantic   │
│ Austin     ┆ 12420 ┆ S    ┆ -97.654303  ┆ … ┆ 64.0        ┆ 1216       ┆ 28.8       ┆ West South │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Central    │
│ Raleigh    ┆ 39580 ┆ S    ┆ -78.46101   ┆ … ┆ 69.6        ┆ 1104       ┆ 28.1       ┆ South      │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Atlantic   │
│ Midland    ┆ 33260 ┆ S    ┆ -101.991236 ┆ … ┆ 70.7        ┆ 1128       ┆ 26.8       ┆ West South │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Central    │
│ California ┆ 15680 ┆ S    ┆ -76.605579  ┆ … ┆ 75.6        ┆ 1266       ┆ 26.4       ┆ South      │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Atlantic   │
│ Andrews    ┆ 11380 ┆ S    ┆ -102.637752 ┆ … ┆ 69.2        ┆ 1066       ┆ 25.0       ┆ West South │
│            ┆       ┆      ┆             ┆   ┆             ┆            ┆            ┆ Central    │
└────────────┴───────┴──────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

9. For each division, compute the average median household income and the number of metros in that division.

In [26]:
(
    dat
    .group_by(c.division)
    .agg(
        num_metros = pl.len(),
        mean_hh_income = c.hh_income_median.mean()
    )
)

shape: (9, 3)
┌────────────────────┬────────────┬────────────────┐
│ division           ┆ num_metros ┆ mean_hh_income │
│ ---                ┆ ---        ┆ ---            │
│ str                ┆ u32        ┆ f64            │
╞════════════════════╪════════════╪════════════════╡
│ New England        ┆ 26         ┆ 73872.653846   │
│ Mountain           ┆ 93         ┆ 63649.376344   │
│ West North Central ┆ 120        ┆ 60065.508333   │
│ Middle Atlantic    ┆ 66         ┆ 62316.318182   │
│ South Atlantic     ┆ 162        ┆ 52636.734568   │
│ East North Central ┆ 160        ┆ 58998.2875     │
│ Pacific            ┆ 82         ┆ 70178.268293   │
│ East South Central ┆ 95         ┆ 49271.568421   │
│ West South Central ┆ 130        ┆ 52675.646154   │
└────────────────────┴────────────┴────────────────┘

10. Find the most populous metro area in each quadrant (i.e., `quad`) of the country.

In [28]:
(
    dat
    .sort(c.pop, descending = True)
    .group_by(c.quad)
    .head(1)
)

shape: (5, 13)
┌──────┬─────────────┬───────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ quad ┆ name        ┆ geoid ┆ lon         ┆ … ┆ percent_ow ┆ rent_1br_m ┆ rent_perc_ ┆ division   │
│ ---  ┆ ---         ┆ ---   ┆ ---         ┆   ┆ n          ┆ edian      ┆ income     ┆ ---        │
│ str  ┆ str         ┆ i64   ┆ f64         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str        │
│      ┆             ┆       ┆             ┆   ┆ f64        ┆ i64        ┆ f64        ┆            │
╞══════╪═════════════╪═══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ O    ┆ San Juan    ┆ 41980 ┆ -66.112516  ┆ … ┆ 69.3       ┆ 379        ┆ 31.9       ┆ South      │
│      ┆             ┆       ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ NE   ┆ New York    ┆ 35620 ┆ -74.101056  ┆ … ┆ 55.3       ┆ 1430       ┆ 31.0       ┆ Middle     │
│      ┆             ┆       ┆             ┆   ┆            ┆            ┆            ┆ Atlantic   │
│ NC   ┆ Chicago     ┆ 16980 ┆ -87.95882   ┆ … ┆ 68.9       ┆ 1060       ┆ 29.0       ┆ East North │
│      ┆             ┆       ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ S    ┆ Dallas      ┆ 19100 ┆ -96.970508  ┆ … ┆ 64.1       ┆ 1106       ┆ 29.1       ┆ West South │
│      ┆             ┆       ┆             ┆   ┆            ┆            ┆            ┆ Central    │
│ W    ┆ Los Angeles ┆ 31080 ┆ -118.148722 ┆ … ┆ 51.3       ┆ 1468       ┆ 33.6       ┆ Pacific    │
└──────┴─────────────┴───────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

11. The population in our dataset is given in millions, create a new column that shows the population in thousands instead.

In [30]:
(
    dat
    .with_columns(act_pop = c.pop * 1000000)
)

shape: (934, 14)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name        ┆ geoid ┆ quad ┆ lon         ┆ … ┆ rent_1br_m ┆ rent_perc_ ┆ division   ┆ act_pop    │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ edian      ┆ income     ┆ ---        ┆ ---        │
│ str         ┆ i64   ┆ str  ┆ f64         ┆   ┆ ---        ┆ ---        ┆ str        ┆ f64        │
│             ┆       ┆      ┆             ┆   ┆ i64        ┆ f64        ┆            ┆            │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ New York    ┆ 35620 ┆ NE   ┆ -74.101056  ┆ … ┆ 1430       ┆ 31.0       ┆ Middle     ┆ 2.0011812e │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Atlantic   ┆ 7          │
│ Los Angeles ┆ 31080 ┆ W    ┆ -118.148722 ┆ … ┆ 1468       ┆ 33.6       ┆ Pacific    ┆ 1.3202558e │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆            ┆ 7          │
│ Chicago     ┆ 16980 ┆ NC   ┆ -87.95882   ┆ … ┆ 1060       ┆ 29.0       ┆ East North ┆ 9.607711e6 │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
│ Dallas      ┆ 19100 ┆ S    ┆ -96.970508  ┆ … ┆ 1106       ┆ 29.1       ┆ West South ┆ 7.54334e6  │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
│ Houston     ┆ 26420 ┆ S    ┆ -95.401574  ┆ … ┆ 997        ┆ 30.0       ┆ West South ┆ 7.048954e6 │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zapata      ┆ 49820 ┆ S    ┆ -99.168533  ┆ … ┆ 321        ┆ 34.6       ┆ West South ┆ 13945.0    │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
│ Ketchikan   ┆ 28540 ┆ O    ┆ -130.927217 ┆ … ┆ 946        ┆ 31.2       ┆ Pacific    ┆ 13939.0    │
│ Craig       ┆ 18780 ┆ W    ┆ -108.207523 ┆ … ┆ 485        ┆ 29.0       ┆ Mountain   ┆ 13240.0    │
│ Vernon      ┆ 46900 ┆ S    ┆ -99.240853  ┆ … ┆ 503        ┆ 22.0       ┆ West South ┆ 12887.0    │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
│ Lamesa      ┆ 29500 ┆ S    ┆ -101.947637 ┆ … ┆ 611        ┆ 34.5       ┆ West South ┆ 12371.0    │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

12. Create a new column that computes the annual rent for a one-bedroom apartment (the current rent column shows monthly rent).

In [31]:
(
    dat
    .with_columns(ann_rent = c.rent_1br_median * 12)
)

shape: (934, 14)
┌─────────────┬───────┬──────┬─────────────┬───┬─────────────┬─────────────┬────────────┬──────────┐
│ name        ┆ geoid ┆ quad ┆ lon         ┆ … ┆ rent_1br_me ┆ rent_perc_i ┆ division   ┆ ann_rent │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ dian        ┆ ncome       ┆ ---        ┆ ---      │
│ str         ┆ i64   ┆ str  ┆ f64         ┆   ┆ ---         ┆ ---         ┆ str        ┆ i64      │
│             ┆       ┆      ┆             ┆   ┆ i64         ┆ f64         ┆            ┆          │
╞═════════════╪═══════╪══════╪═════════════╪═══╪═════════════╪═════════════╪════════════╪══════════╡
│ New York    ┆ 35620 ┆ NE   ┆ -74.101056  ┆ … ┆ 1430        ┆ 31.0        ┆ Middle     ┆ 17160    │
│             ┆       ┆      ┆             ┆   ┆             ┆             ┆ Atlantic   ┆          │
│ Los Angeles ┆ 31080 ┆ W    ┆ -118.148722 ┆ … ┆ 1468        ┆ 33.6        ┆ Pacific    ┆ 17616    │
│ Chicago     ┆ 16980 ┆ NC   ┆ -87.95882   ┆ … ┆ 1060        ┆ 29.0        ┆ East North ┆ 12720    │
│             ┆       ┆      ┆             ┆   ┆             ┆             ┆ Central    ┆          │
│ Dallas      ┆ 19100 ┆ S    ┆ -96.970508  ┆ … ┆ 1106        ┆ 29.1        ┆ West South ┆ 13272    │
│             ┆       ┆      ┆             ┆   ┆             ┆             ┆ Central    ┆          │
│ Houston     ┆ 26420 ┆ S    ┆ -95.401574  ┆ … ┆ 997         ┆ 30.0        ┆ West South ┆ 11964    │
│             ┆       ┆      ┆             ┆   ┆             ┆             ┆ Central    ┆          │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …           ┆ …           ┆ …          ┆ …        │
│ Zapata      ┆ 49820 ┆ S    ┆ -99.168533  ┆ … ┆ 321         ┆ 34.6        ┆ West South ┆ 3852     │
│             ┆       ┆      ┆             ┆   ┆             ┆             ┆ Central    ┆          │
│ Ketchikan   ┆ 28540 ┆ O    ┆ -130.927217 ┆ … ┆ 946         ┆ 31.2        ┆ Pacific    ┆ 11352    │
│ Craig       ┆ 18780 ┆ W    ┆ -108.207523 ┆ … ┆ 485         ┆ 29.0        ┆ Mountain   ┆ 5820     │
│ Vernon      ┆ 46900 ┆ S    ┆ -99.240853  ┆ … ┆ 503         ┆ 22.0        ┆ West South ┆ 6036     │
│             ┆       ┆      ┆             ┆   ┆             ┆             ┆ Central    ┆          │
│ Lamesa      ┆ 29500 ┆ S    ┆ -101.947637 ┆ … ┆ 611         ┆ 34.5        ┆ West South ┆ 7332     │
│             ┆       ┆      ┆             ┆   ┆             ┆             ┆ Central    ┆          │
└─────────────┴───────┴──────┴─────────────┴───┴─────────────┴─────────────┴────────────┴──────────┘

13. The median household income is given as an exact figure, but it can be useful to round it. Create a new column that rounds the income to the nearest $10,000. Hint: Use the same integer division technique we used for computing decades from years.

In [32]:
(
    dat
    .with_columns(income_rounded = c.hh_income_median // 10000 * 10000)
)

shape: (934, 14)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name        ┆ geoid ┆ quad ┆ lon         ┆ … ┆ rent_1br_m ┆ rent_perc_ ┆ division   ┆ income_rou │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ edian      ┆ income     ┆ ---        ┆ nded       │
│ str         ┆ i64   ┆ str  ┆ f64         ┆   ┆ ---        ┆ ---        ┆ str        ┆ ---        │
│             ┆       ┆      ┆             ┆   ┆ i64        ┆ f64        ┆            ┆ i64        │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ New York    ┆ 35620 ┆ NE   ┆ -74.101056  ┆ … ┆ 1430       ┆ 31.0       ┆ Middle     ┆ 80000      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Atlantic   ┆            │
│ Los Angeles ┆ 31080 ┆ W    ┆ -118.148722 ┆ … ┆ 1468       ┆ 33.6       ┆ Pacific    ┆ 80000      │
│ Chicago     ┆ 16980 ┆ NC   ┆ -87.95882   ┆ … ┆ 1060       ┆ 29.0       ┆ East North ┆ 70000      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
│ Dallas      ┆ 19100 ┆ S    ┆ -96.970508  ┆ … ┆ 1106       ┆ 29.1       ┆ West South ┆ 70000      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
│ Houston     ┆ 26420 ┆ S    ┆ -95.401574  ┆ … ┆ 997        ┆ 30.0       ┆ West South ┆ 70000      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ Zapata      ┆ 49820 ┆ S    ┆ -99.168533  ┆ … ┆ 321        ┆ 34.6       ┆ West South ┆ 30000      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
│ Ketchikan   ┆ 28540 ┆ O    ┆ -130.927217 ┆ … ┆ 946        ┆ 31.2       ┆ Pacific    ┆ 70000      │
│ Craig       ┆ 18780 ┆ W    ┆ -108.207523 ┆ … ┆ 485        ┆ 29.0       ┆ Mountain   ┆ 50000      │
│ Vernon      ┆ 46900 ┆ S    ┆ -99.240853  ┆ … ┆ 503        ┆ 22.0       ┆ West South ┆ 40000      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
│ Lamesa      ┆ 29500 ┆ S    ┆ -101.947637 ┆ … ┆ 611        ┆ 34.5       ┆ West South ┆ 40000      │
│             ┆       ┆      ┆             ┆   ┆            ┆            ┆ Central    ┆            │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

14. Now, count how many metro areas fall into each income bracket (rounded to the nearest $10,000).

In [40]:
(
    dat
    .with_columns(income_rounded = c.hh_income_median // 10000 * 10000)
    .group_by(c.income_rounded)
    .agg(
        count = pl.len()
    )
)

shape: (13, 2)
┌────────────────┬───────┐
│ income_rounded ┆ count │
│ ---            ┆ ---   │
│ i64            ┆ u32   │
╞════════════════╪═══════╡
│ 20000          ┆ 2     │
│ 100000         ┆ 3     │
│ 30000          ┆ 38    │
│ 60000          ┆ 226   │
│ 50000          ┆ 353   │
│ …              ┆ …     │
│ 80000          ┆ 41    │
│ 110000         ┆ 2     │
│ 70000          ┆ 80    │
│ 90000          ┆ 11    │
│ 120000         ┆ 1     │
└────────────────┴───────┘

15. For each census division, find the metro area with the lowest median rent. Sort the final result alphabetically by division name.

In [41]:
(
    dat
    .sort(c.rent_1br_median, descending = True)
    .group_by(c.division)
    .head(1)
    .sort(c.division)
)

shape: (9, 13)
┌─────────────┬─────────────┬───────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ division    ┆ name        ┆ geoid ┆ quad ┆ … ┆ hh_income_ ┆ percent_ow ┆ rent_1br_m ┆ rent_perc_ │
│ ---         ┆ ---         ┆ ---   ┆ ---  ┆   ┆ median     ┆ n          ┆ edian      ┆ income     │
│ str         ┆ str         ┆ i64   ┆ str  ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│             ┆             ┆       ┆      ┆   ┆ i64        ┆ f64        ┆ i64        ┆ f64        │
╞═════════════╪═════════════╪═══════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ East North  ┆ Ann Arbor   ┆ 11460 ┆ NC   ┆ … ┆ 79198      ┆ 65.8       ┆ 1072       ┆ 31.4       │
│ Central     ┆             ┆       ┆      ┆   ┆            ┆            ┆            ┆            │
│ East South  ┆ Nashville   ┆ 34980 ┆ S    ┆ … ┆ 72537      ┆ 68.7       ┆ 1083       ┆ 29.1       │
│ Central     ┆             ┆       ┆      ┆   ┆            ┆            ┆            ┆            │
│ Middle      ┆ New York    ┆ 35620 ┆ NE   ┆ … ┆ 86445      ┆ 55.3       ┆ 1430       ┆ 31.0       │
│ Atlantic    ┆             ┆       ┆      ┆   ┆            ┆            ┆            ┆            │
│ Mountain    ┆ Boulder     ┆ 14500 ┆ W    ┆ … ┆ 92466      ┆ 64.7       ┆ 1398       ┆ 33.6       │
│ New England ┆ Boston      ┆ 14460 ┆ NE   ┆ … ┆ 99039      ┆ 66.4       ┆ 1390       ┆ 29.5       │
│ Pacific     ┆ San Jose    ┆ 41940 ┆ W    ┆ … ┆ 138370     ┆ 58.5       ┆ 2227       ┆ 27.8       │
│ South       ┆ Washington  ┆ 47900 ┆ S    ┆ … ┆ 111252     ┆ 67.4       ┆ 1601       ┆ 28.8       │
│ Atlantic    ┆             ┆       ┆      ┆   ┆            ┆            ┆            ┆            │
│ West North  ┆ Minneapolis ┆ 33460 ┆ NC   ┆ … ┆ 87397      ┆ 75.0       ┆ 1035       ┆ 28.5       │
│ Central     ┆             ┆       ┆      ┆   ┆            ┆            ┆            ┆            │
│ West South  ┆ Austin      ┆ 12420 ┆ S    ┆ … ┆ 85398      ┆ 64.0       ┆ 1216       ┆ 28.8       │
│ Central     ┆             ┆       ┆      ┆   ┆            ┆            ┆            ┆            │
└─────────────┴─────────────┴───────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

16. Find the divisions that have more than 75 metro areas. Show the average home ownership rate for each of these divisions, sorted from highest to lowest ownership rate.

In [43]:
(
    dat
    avg_home_own = c.percent_own.mean
    .
)

TypeError: cannot create expression literal for value of type method.

Hint: Pass `allow_object=True` to accept any value and create a literal of type Object.

17. For each division with more than 75 metro areas, show the name of the metro with the highest population density. Use `print_rows` to display all results.