<a href="https://colab.research.google.com/github/tettehdaniel/python-labs/blob/main/Notebooks/Notebook05_DataManipulation3_SV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 05 — Data Manipulation Three

**Main Objective**

1. Aggregation/Summarizing
2. Piping

## Setup

Please run the setup code below

In [1]:
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py

from funs import *

In [2]:
import numpy as np
import polars as pl

from plotnine import *
from polars import col as c
theme_set(theme_minimal())

path = "https://raw.githubusercontent.com/ajcollins16/DSST289_Fall2026_AJC/refs/heads/main/"

In [41]:
dat = pl.read_csv(path + "Data/criterion.csv").filter(~c.rating_imdb.is_null())

## Summarizing and Piping

Another day another set of new data manipulation techniques to work through. Specifically, we will work through the process of summarizing data with the `.agg` function and broadly discussing the `.pipe` function. What we mean by summarizing is that many times we want to get some descriptive statistics (i.e., mean, median, mode, variance, standard deviation, quantiles, etc.) or other meaningful pieces of information (i.e., max, min, sample size, correlation, etc.) on a variable of interest out.

Today's dataset is a film dataset that contains information about movies like title, director, release year, runtime, and the IMDB rating (at the time).

In [4]:
dat

shape: (1_470, 18)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ imdb_id    ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia ┆ budget_ra ┆ box_offic │
│ ---        ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ _extract  ┆ w         ┆ e_raw     │
│ str        ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆      ┆            ┆   ┆ ---        ┆ str       ┆ i64       ┆ i64       │
│            ┆            ┆      ┆            ┆   ┆ str        ┆           ┆           ┆           │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ tt0012349  ┆ The Kid    ┆ 1921 ┆ None|Engli ┆ … ┆ 1921       ┆ The Kid   ┆ 250000    ┆ null      │
│            ┆            ┆      ┆ sh         ┆   ┆ silent     ┆ is a 1921 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ film by    ┆ American  ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ Charlie    ┆ sil…      ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ Ch…        ┆           ┆           ┆           │
│ tt0012364  ┆ The        ┆ 1921 ┆ None|Swedi ┆ … ┆ 1921 film  ┆ The       ┆ null      ┆ null      │
│            ┆ Phantom    ┆      ┆ sh         ┆   ┆ by Victor  ┆ Phantom   ┆           ┆           │
│            ┆ Carriage   ┆      ┆            ┆   ┆ Sjöström   ┆ Carriage  ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ is a      ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 1921…     ┆           ┆           │
│ tt0013257  ┆ Häxan      ┆ 1922 ┆ Swedish|Da ┆ … ┆ Swedish    ┆ Häxan is  ┆ 2000000   ┆ null      │
│            ┆            ┆      ┆ nish       ┆   ┆ 1922       ┆ a 1922    ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ silent     ┆ Swedish-D ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ horror     ┆ anish…    ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ ess…       ┆           ┆           ┆           │
│ tt0014429  ┆ Safety     ┆ 1923 ┆ English    ┆ … ┆ 1923       ┆ Safety    ┆ 121000    ┆ null      │
│            ┆ Last!      ┆      ┆            ┆   ┆ American   ┆ Last! is  ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ silent     ┆ a 1923    ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ romantic … ┆ America…  ┆           ┆           │
│ tt0014624  ┆ A Woman of ┆ 1923 ┆ English    ┆ … ┆ 1923 drama ┆ A Woman   ┆ 351000    ┆ 634000    │
│            ┆ Paris: A   ┆      ┆            ┆   ┆ film by    ┆ of Paris  ┆           ┆           │
│            ┆ Drama of   ┆      ┆            ┆   ┆ Charlie    ┆ is a 1923 ┆           ┆           │
│            ┆ F…         ┆      ┆            ┆   ┆ Cha…       ┆ sil…      ┆           ┆           │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ tt27958252 ┆ Caught by  ┆ 2024 ┆ Mandarin|E ┆ … ┆ 2024 film  ┆ Caught by ┆ null      ┆ null      │
│            ┆ the Tides  ┆      ┆ nglish     ┆   ┆ by Jia     ┆ the Tides ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ Zhangke    ┆ is a 2024 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ …         ┆           ┆           │
│ tt28607951 ┆ Anora      ┆ 2024 ┆ English|Ru ┆ … ┆ 2024 film  ┆ Anora is  ┆ null      ┆ null      │
│            ┆            ┆      ┆ ssian|Arme ┆   ┆ by Sean    ┆ a 2024    ┆           ┆           │
│            ┆            ┆      ┆ nian       ┆   ┆ Baker      ┆ American  ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ roman…    ┆           ┆           │
│ tt28618488 ┆ Vermiglio  ┆ 2024 ┆ Italian|La ┆ … ┆ 2024 film  ┆ Vermiglio ┆ null      ┆ null      │
│            ┆            ┆      ┆ tin        ┆   ┆ by Maura   ┆ , also    ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ Delpero    ┆ known as  ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ The …     ┆           ┆           │
│ tt32085997 ┆ Misericord ┆ 2024 ┆ French     ┆ … ┆ 2024 film  ┆ Misericor ┆ null      ┆ null      │
│            ┆ ia         ┆      ┆            ┆   ┆ by Alain   ┆ dia is a  ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆ Guiraudie  ┆ 2024      ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ black c…  ┆           ┆           │
│ tt32086077 ┆ All We     ┆ 2024 ┆ Malayalam| ┆ … ┆ 2024 film  ┆ All We    ┆ null      ┆ null      │
│            ┆ Imagine as ┆      ┆ Hindi|Mara ┆   ┆ by Payal   ┆ Imagine   ┆           ┆           │
│            ┆ Light      ┆      ┆ thi|Englis ┆   ┆ Kapadia    ┆ as Light  ┆           ┆           │
│            ┆            ┆      ┆ …          ┆   ┆            ┆ is a 2…   ┆           ┆           │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

### Questions

1. Start by sorting the films by their IMDB rating, with the lowest-rated film at the top.

In [5]:
(
    dat
    .sort(c.rating_imdb)
)

shape: (1_470, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0062492 ┆ Wild 90    ┆ 1968 ┆ English    ┆ … ┆ 1968 film  ┆ Wild 90 is ┆ null      ┆ null      │
│           ┆            ┆      ┆            ┆   ┆ by Norman  ┆ a 1968 exp ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Mailer     ┆ erimental… ┆           ┆           │
│ tt0064373 ┆ All        ┆ 1969 ┆ Japanese   ┆ … ┆ 1969 film  ┆ All        ┆ null      ┆ null      │
│           ┆ Monsters   ┆      ┆            ┆   ┆ by Ishirō  ┆ Monsters   ┆           ┆           │
│           ┆ Attack     ┆      ┆            ┆   ┆ Honda      ┆ Attack  is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ a 1969…    ┆           ┆           │
│ tt0063195 ┆ Genocide   ┆ 1968 ┆ Japanese   ┆ … ┆ 1968       ┆ Genocide   ┆ null      ┆ null      │
│           ┆            ┆      ┆            ┆   ┆ Japanese   ┆ is a 1968  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ Japanese   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ s…         ┆           ┆           │
│ tt0064625 ┆ Maidstone  ┆ 1970 ┆ English    ┆ … ┆ 1970 film  ┆ Maidstone  ┆ null      ┆ null      │
│           ┆            ┆      ┆            ┆   ┆ by Norman  ┆ is a 1970  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Mailer     ┆ American   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ i…         ┆           ┆           │
│ tt2006181 ┆ Jellyfish  ┆ 2013 ┆ Japanese   ┆ … ┆ 2013       ┆ Jellyfish  ┆ null      ┆ null      │
│           ┆ Eyes       ┆      ┆            ┆   ┆ Japanese   ┆ Eyes  is a ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ 2013 Japa… ┆           ┆           │
│ …         ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ tt0048434 ┆ Night and  ┆ 1956 ┆ French     ┆ … ┆ 1956       ┆ Night and  ┆ null      ┆ null      │
│           ┆ Fog        ┆      ┆            ┆   ┆ French     ┆ Fog is a   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ 1956       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ French…    ┆           ┆           │
│ tt0056058 ┆ Harakiri   ┆ 1962 ┆ Japanese   ┆ … ┆ Japanese   ┆ Harakiri   ┆ null      ┆ 15000     │
│           ┆            ┆      ┆            ┆   ┆ jidaigeki  ┆ is a 1962  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ Japanese   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ j…         ┆           ┆           │
│ tt0102926 ┆ The        ┆ 1991 ┆ English|La ┆ … ┆ 1991       ┆ The        ┆ 19000000  ┆ 130742922 │
│           ┆ Silence of ┆      ┆ tin        ┆   ┆ horror     ┆ Silence of ┆           ┆           │
│           ┆ the Lambs  ┆      ┆            ┆   ┆ film by    ┆ the Lambs  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Jonathan   ┆ is a …     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ D…         ┆            ┆           ┆           │
│ tt0090015 ┆ Shoah      ┆ 1985 ┆ German|Heb ┆ … ┆ 1985       ┆ Shoah is a ┆ null      ┆ null      │
│           ┆            ┆      ┆ rew|Polish ┆   ┆ French doc ┆ 1985       ┆           ┆           │
│           ┆            ┆      ┆ |Yiddish|F ┆   ┆ umentary   ┆ French     ┆           ┆           │
│           ┆            ┆      ┆ …          ┆   ┆ film b…    ┆ documen…   ┆           ┆           │
│ tt0050083 ┆ 12 Angry   ┆ 1957 ┆ English    ┆ … ┆ American   ┆ 12 Angry   ┆ 340000    ┆ null      │
│           ┆ Men        ┆      ┆            ┆   ┆ legal      ┆ Men is a   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ drama film ┆ 1957       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ by S…      ┆ America…   ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

2. Now, sort the films by runtime with the longest films at the top. Note, use the `.drop_nulls` function to make sure you don't have movies at the top with no runtime given.

In [31]:
(
    dat
    .drop_nulls(c.runtime_raw)
    .sort(c.runtime_raw, descending = True)
)

shape: (1_407, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0090015 ┆ Shoah      ┆ 1985 ┆ German|Heb ┆ … ┆ 1985       ┆ Shoah is a ┆ null      ┆ null      │
│           ┆            ┆      ┆ rew|Polish ┆   ┆ French doc ┆ 1985       ┆           ┆           │
│           ┆            ┆      ┆ |Yiddish|F ┆   ┆ umentary   ┆ French     ┆           ┆           │
│           ┆            ┆      ┆ …          ┆   ┆ film b…    ┆ documen…   ┆           ┆           │
│ tt0063794 ┆ War and    ┆ 1965 ┆ Russian|Ge ┆ … ┆ 1967 film  ┆ War and    ┆ 8291712   ┆ 58000000  │
│           ┆ Peace      ┆      ┆ rman|Frenc ┆   ┆ by Sergei  ┆ Peace is a ┆           ┆           │
│           ┆            ┆      ┆ h          ┆   ┆ Bondarchuk ┆ 1965–1967  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ S…         ┆           ┆           │
│ tt0025509 ┆ Les        ┆ 1934 ┆ French     ┆ … ┆ 1934       ┆ Les        ┆ null      ┆ null      │
│           ┆ Misérables ┆      ┆            ┆   ┆ French     ┆ Misérables ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ is a 1934  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ Frenc…     ┆           ┆           │
│ tt0101985 ┆ A Brighter ┆ 1991 ┆ Mandarin|M ┆ … ┆ 1991       ┆ A Brighter ┆ null      ┆ null      │
│           ┆ Summer Day ┆      ┆ in Nan|Sha ┆   ┆ Taiwanese  ┆ Summer Day ┆           ┆           │
│           ┆            ┆      ┆ nghainese| ┆   ┆ epic comin ┆ is a 199…  ┆           ┆           │
│           ┆            ┆      ┆ …          ┆   ┆ g-of-…     ┆            ┆           ┆           │
│ tt0070359 ┆ The Mother ┆ 1973 ┆ French     ┆ … ┆ 1973       ┆ The Mother ┆ null      ┆ null      │
│           ┆ and the    ┆      ┆            ┆   ┆ French     ┆ and the    ┆           ┆           │
│           ┆ Whore      ┆      ┆            ┆   ┆ film       ┆ Whore is a ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ …         ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ tt0056662 ┆ Vive le    ┆ 1962 ┆ French     ┆ … ┆ 1962       ┆ Vive le    ┆ null      ┆ null      │
│           ┆ tour       ┆      ┆            ┆   ┆ French     ┆ Tour is a  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ 1962       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ French …   ┆           ┆           │
│ tt0075122 ┆ The        ┆ 1976 ┆ Persian    ┆ … ┆ 1976       ┆ The        ┆ null      ┆ null      │
│           ┆ Colours    ┆      ┆            ┆   ┆ Iranian    ┆ Colours is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ a 1976     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ Iranian …  ┆           ┆           │
│ tt0063551 ┆ Saute ma   ┆ 1971 ┆ French     ┆ … ┆ Belgian    ┆ Chantal    ┆ null      ┆ null      │
│           ┆ ville      ┆      ┆            ┆   ┆ film       ┆ Anne       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ director,  ┆ Akerman    ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ screenw…   ┆ was a Bel… ┆           ┆           │
│ tt0068354 ┆ La chambre ┆ 1972 ┆ French     ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│ tt0066127 ┆ The Bread  ┆ 1970 ┆ None       ┆ … ┆ 1970 film  ┆ The Bread  ┆ null      ┆ null      │
│           ┆ and Alley  ┆      ┆            ┆   ┆            ┆ and Alley  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ is a 1970  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ …          ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

3. Now select only the films that are less than 60 minutes long (i.e., short films).

In [32]:
(
    dat
    .filter(c.runtime_raw < 60)
)

shape: (26, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0021576 ┆ À Propos   ┆ 1930 ┆ None       ┆ … ┆ 1930 film  ┆ À propos   ┆ null      ┆ null      │
│           ┆ de Nice    ┆      ┆            ┆   ┆            ┆ de Nice is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ a 1930     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ sil…       ┆           ┆           │
│ tt0022036 ┆ Flunky,    ┆ 1931 ┆ None|Japan ┆ … ┆ 1931       ┆ Flunky,    ┆ null      ┆ null      │
│           ┆ Work Hard! ┆      ┆ ese        ┆   ┆ Japanese   ┆ Work Hard! ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ is a 1931  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ tt0024803 ┆ Zero for   ┆ 1933 ┆ French     ┆ … ┆ 1933       ┆ Zero for   ┆ null      ┆ null      │
│           ┆ Conduct    ┆      ┆            ┆   ┆ French     ┆ Conduct is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ a 1933     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ Fre…       ┆           ┆           │
│ tt0028445 ┆ A Day in   ┆ 1936 ┆ French     ┆ … ┆ 1946       ┆ Partie de  ┆ null      ┆ null      │
│           ┆ the        ┆      ┆            ┆   ┆ French     ┆ campagne   ┆           ┆           │
│           ┆ Country    ┆      ┆            ┆   ┆ film       ┆ is a       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ French…    ┆           ┆           │
│ tt0038182 ┆ The Men    ┆ 1945 ┆ Japanese   ┆ … ┆ 1945       ┆ The Men    ┆ null      ┆ null      │
│           ┆ Who Tread  ┆      ┆            ┆   ┆ Japanese   ┆ Who Tread  ┆           ┆           │
│           ┆ on the     ┆      ┆            ┆   ┆ film by    ┆ on the     ┆           ┆           │
│           ┆ Tiger…     ┆      ┆            ┆   ┆ Akira Ku…  ┆ Tiger…     ┆           ┆           │
│ …         ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ tt0079704 ┆ Paul       ┆ 1979 ┆ English|Ma ┆ … ┆ 1979 film  ┆ Paul       ┆ null      ┆ null      │
│           ┆ Robeson:   ┆      ┆ ndarin     ┆   ┆            ┆ Robeson:   ┆           ┆           │
│           ┆ Tribute to ┆      ┆            ┆   ┆            ┆ Tribute to ┆           ┆           │
│           ┆ an Ar…     ┆      ┆            ┆   ┆            ┆ an Ar…     ┆           ┆           │
│ tt0081204 ┆ Mur murs   ┆ 1981 ┆ French|Eng ┆ … ┆ 1980 docum ┆ Mur Murs   ┆ null      ┆ null      │
│           ┆            ┆      ┆ lish|Itali ┆   ┆ entary     ┆ is a 1981  ┆           ┆           │
│           ┆            ┆      ┆ an|Spanish ┆   ┆ film by    ┆ documentar ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Agnès…     ┆ y…         ┆           ┆           │
│ tt0083727 ┆ Chambre    ┆ 1982 ┆ English|Fr ┆ … ┆ 1982       ┆ Room 666   ┆ null      ┆ null      │
│           ┆ 666        ┆      ┆ ench|Germa ┆   ┆ French     ┆ is a 1982  ┆           ┆           │
│           ┆            ┆      ┆ n|Italian| ┆   ┆ film       ┆ documentar ┆           ┆           │
│           ┆            ┆      ┆ …          ┆   ┆            ┆ y…         ┆           ┆           │
│ tt0085641 ┆ Fellow     ┆ 1983 ┆ Persian    ┆ … ┆ 1983       ┆ Fellow     ┆ null      ┆ null      │
│           ┆ Citizen    ┆      ┆            ┆   ┆ Iranian    ┆ Citizen is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ a 1983     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ Irani…     ┆           ┆           │
│ tt0111460 ┆ Total      ┆ 1994 ┆ Finnish|En ┆ … ┆ 1994       ┆ Total      ┆ null      ┆ null      │
│           ┆ Balalaika  ┆      ┆ glish|Fren ┆   ┆ Finnish    ┆ Balalaika  ┆           ┆           │
│           ┆ Show       ┆      ┆ ch|Russian ┆   ┆ film       ┆ Show is a  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ 1994…      ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

4. Now select the films that are directed by Charles Chaplin.

In [33]:
(
    dat
    .filter(c.director == "Charles Chaplin")
)

shape: (8, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0012349 ┆ The Kid    ┆ 1921 ┆ None|Engli ┆ … ┆ 1921       ┆ The Kid is ┆ 250000    ┆ null      │
│           ┆            ┆      ┆ sh         ┆   ┆ silent     ┆ a 1921     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film by    ┆ American   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie    ┆ sil…       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Ch…        ┆            ┆           ┆           │
│ tt0014624 ┆ A Woman of ┆ 1923 ┆ English    ┆ … ┆ 1923 drama ┆ A Woman of ┆ 351000    ┆ 634000    │
│           ┆ Paris: A   ┆      ┆            ┆   ┆ film by    ┆ Paris is a ┆           ┆           │
│           ┆ Drama of   ┆      ┆            ┆   ┆ Charlie    ┆ 1923 sil…  ┆           ┆           │
│           ┆ F…         ┆      ┆            ┆   ┆ Cha…       ┆            ┆           ┆           │
│ tt0018773 ┆ The Circus ┆ 1928 ┆ None|Engli ┆ … ┆ 1928 film  ┆ The Circus ┆ null      ┆ null      │
│           ┆            ┆      ┆ sh         ┆   ┆ by Charlie ┆ is a 1928  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Chaplin    ┆ silent ro… ┆           ┆           │
│ tt0021749 ┆ City       ┆ 1931 ┆ None|Engli ┆ … ┆ 1931       ┆ City       ┆ 1500000   ┆ 5000000   │
│           ┆ Lights     ┆      ┆ sh         ┆   ┆ American   ┆ Lights is  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ silent     ┆ a 1931     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ American…  ┆           ┆           │
│ tt0027977 ┆ Modern     ┆ 1936 ┆ English    ┆ … ┆ 1936       ┆ Modern     ┆ 1500000   ┆ 1400000   │
│           ┆ Times      ┆      ┆            ┆   ┆ comedy     ┆ Times is a ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film by    ┆ 1936       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie    ┆ America…   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Ch…        ┆            ┆           ┆           │
│ tt0032553 ┆ The Great  ┆ 1940 ┆ English|Es ┆ … ┆ 1940       ┆ The Great  ┆ 2000000   ┆ 5000000   │
│           ┆ Dictator   ┆      ┆ peranto|La ┆   ┆ American   ┆ Dictator   ┆           ┆           │
│           ┆            ┆      ┆ tin        ┆   ┆ film by    ┆ is a 1940  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie …  ┆ A…         ┆           ┆           │
│ tt0039631 ┆ Monsieur   ┆ 1947 ┆ English|Fr ┆ … ┆ 1947 film  ┆ Monsieur   ┆ 2000000   ┆ null      │
│           ┆ Verdoux    ┆      ┆ ench|Latin ┆   ┆ by Charlie ┆ Verdoux is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Chaplin    ┆ a 1947     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ Ame…       ┆           ┆           │
│ tt0044837 ┆ Limelight  ┆ 1952 ┆ English    ┆ … ┆ 1952 film  ┆ Limelight  ┆ 900000    ┆ 1000000   │
│           ┆            ┆      ┆            ┆   ┆ by Charlie ┆ is a 1952  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Chaplin    ┆ American   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ c…         ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

5. Now select the films direct by either Charles Chaplin or Jean-Luc Godard.

In [35]:
(
    dat
    .filter((c.director == "Charles Chaplin") | (c.director == "Jean-Luc Godard"))
)

shape: (19, 18)
┌───────────┬────────────┬──────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ imdb_id   ┆ title      ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ wikipedia_ ┆ budget_ra ┆ box_offic │
│ ---       ┆ ---        ┆ ---  ┆ ---        ┆   ┆ descriptio ┆ extract    ┆ w         ┆ e_raw     │
│ str       ┆ str        ┆ i64  ┆ str        ┆   ┆ n          ┆ ---        ┆ ---       ┆ ---       │
│           ┆            ┆      ┆            ┆   ┆ ---        ┆ str        ┆ i64       ┆ i64       │
│           ┆            ┆      ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞═══════════╪════════════╪══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ tt0012349 ┆ The Kid    ┆ 1921 ┆ None|Engli ┆ … ┆ 1921       ┆ The Kid is ┆ 250000    ┆ null      │
│           ┆            ┆      ┆ sh         ┆   ┆ silent     ┆ a 1921     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film by    ┆ American   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie    ┆ sil…       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Ch…        ┆            ┆           ┆           │
│ tt0014624 ┆ A Woman of ┆ 1923 ┆ English    ┆ … ┆ 1923 drama ┆ A Woman of ┆ 351000    ┆ 634000    │
│           ┆ Paris: A   ┆      ┆            ┆   ┆ film by    ┆ Paris is a ┆           ┆           │
│           ┆ Drama of   ┆      ┆            ┆   ┆ Charlie    ┆ 1923 sil…  ┆           ┆           │
│           ┆ F…         ┆      ┆            ┆   ┆ Cha…       ┆            ┆           ┆           │
│ tt0018773 ┆ The Circus ┆ 1928 ┆ None|Engli ┆ … ┆ 1928 film  ┆ The Circus ┆ null      ┆ null      │
│           ┆            ┆      ┆ sh         ┆   ┆ by Charlie ┆ is a 1928  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Chaplin    ┆ silent ro… ┆           ┆           │
│ tt0021749 ┆ City       ┆ 1931 ┆ None|Engli ┆ … ┆ 1931       ┆ City       ┆ 1500000   ┆ 5000000   │
│           ┆ Lights     ┆      ┆ sh         ┆   ┆ American   ┆ Lights is  ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ silent     ┆ a 1931     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film       ┆ American…  ┆           ┆           │
│ tt0027977 ┆ Modern     ┆ 1936 ┆ English    ┆ … ┆ 1936       ┆ Modern     ┆ 1500000   ┆ 1400000   │
│           ┆ Times      ┆      ┆            ┆   ┆ comedy     ┆ Times is a ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ film by    ┆ 1936       ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Charlie    ┆ America…   ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Ch…        ┆            ┆           ┆           │
│ …         ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ tt0060675 ┆ Masculine  ┆ 1966 ┆ French|Swe ┆ … ┆ 1966 film  ┆ Masculin   ┆ null      ┆ null      │
│           ┆ Feminine   ┆      ┆ dish|Engli ┆   ┆ by         ┆ féminin:   ┆           ┆           │
│           ┆            ┆      ┆ sh         ┆   ┆ Jean-Luc   ┆ 15         ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Godard     ┆ Specific … ┆           ┆           │
│ tt0060304 ┆ 2 or 3     ┆ 1967 ┆ French|Ita ┆ … ┆ 1967 film  ┆ Two or     ┆ null      ┆ null      │
│           ┆ Things I   ┆      ┆ lian|Engli ┆   ┆ by         ┆ Three      ┆           ┆           │
│           ┆ Know About ┆      ┆ sh         ┆   ┆ Jean-Luc   ┆ Things I   ┆           ┆           │
│           ┆ Her        ┆      ┆            ┆   ┆ Godard     ┆ Know Abo…  ┆           ┆           │
│ tt0062480 ┆ Weekend    ┆ 1967 ┆ French     ┆ … ┆ Film by    ┆ Weekend is ┆ null      ┆ null      │
│           ┆            ┆      ┆            ┆   ┆ Jean-Luc   ┆ a 1967     ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆ Godard     ┆ postmodern ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ b…         ┆           ┆           │
│ tt0079854 ┆ Every Man  ┆ 1980 ┆ French|Ita ┆ … ┆ 1980       ┆ Every Man  ┆ null      ┆ null      │
│           ┆ for        ┆      ┆ lian       ┆   ┆ French     ┆ for        ┆           ┆           │
│           ┆ Himself    ┆      ┆            ┆   ┆ film       ┆ Himself is ┆           ┆           │
│           ┆            ┆      ┆            ┆   ┆            ┆ a 198…     ┆           ┆           │
│ tt0093349 ┆ King Lear  ┆ 1987 ┆ French|Eng ┆ … ┆ 1987 film  ┆ King Lear  ┆ null      ┆ null      │
│           ┆            ┆      ┆ lish|Russi ┆   ┆ directed   ┆ is a 1987  ┆           ┆           │
│           ┆            ┆      ┆ an|Japanes ┆   ┆ by         ┆ film       ┆           ┆           │
│           ┆            ┆      ┆ …          ┆   ┆ Jean-Luc…  ┆ direc…     ┆           ┆           │
└───────────┴────────────┴──────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

6. For each director, compute the average IMDB ratings of their films and the number of films they have in their collection.

In [15]:
(
    dat
    .group_by(c.director)
    .agg(
        num_movie = pl.len(),
        mean_imdb = c.rating_imdb.mean()
    )
)

shape: (650, 3)
┌─────────────────────────────────┬───────────┬───────────┐
│ director                        ┆ num_movie ┆ mean_imdb │
│ ---                             ┆ ---       ┆ ---       │
│ str                             ┆ u32       ┆ f64       │
╞═════════════════════════════════╪═══════════╪═══════════╡
│ Michael Powell                  ┆ 2         ┆ 7.45      │
│ Idrissa Ouedraogo               ┆ 1         ┆ 6.5       │
│ Ted Wilde                       ┆ 1         ┆ 7.6       │
│ Donna Deitch                    ┆ 1         ┆ 7.1       │
│ William Dieterle                ┆ 1         ┆ 7.6       │
│ …                               ┆ …         ┆ …         │
│ Ermanno Olmi                    ┆ 3         ┆ 7.766667  │
│ Tokuzô Tanaka                   ┆ 3         ┆ 7.233333  │
│ Bruce Lee                       ┆ 1         ┆ 7.1       │
│ Yoshiyuki Kuroda                ┆ 1         ┆ 7.3       │
│ Chantal Akerman|Samy Szlingerb… ┆ 1         ┆ 6.7       │
└─────────────────────────────────┴───────────┴───────────┘

One interesting thing that is often done with movies that we can practice here is to group movies by decade rather than individual years. To accomplish this we can use the expression `c.year // 10 * 10`. The `//` operator in Python performans something called **integer division**, which divides the numbers and then drops the decimals/remainder.

7. As an example can you integer divide 1987 from 10 below

In [18]:
1987 // 10 * 10

1980

7. What do you get as output?

**Answer (Q7):**

8. Create a new column in our dataset containing the decade each film was released.

In [19]:
(
    dat
    .with_columns(decade = c.year // 10 * 10)
)

shape: (1_470, 19)
┌────────────┬─────────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬────────┐
│ imdb_id    ┆ title       ┆ year ┆ language   ┆ … ┆ wikipedia_ ┆ budget_raw ┆ box_office ┆ decade │
│ ---        ┆ ---         ┆ ---  ┆ ---        ┆   ┆ extract    ┆ ---        ┆ _raw       ┆ ---    │
│ str        ┆ str         ┆ i64  ┆ str        ┆   ┆ ---        ┆ i64        ┆ ---        ┆ i64    │
│            ┆             ┆      ┆            ┆   ┆ str        ┆            ┆ i64        ┆        │
╞════════════╪═════════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪════════╡
│ tt0012349  ┆ The Kid     ┆ 1921 ┆ None|Engli ┆ … ┆ The Kid is ┆ 250000     ┆ null       ┆ 1920   │
│            ┆             ┆      ┆ sh         ┆   ┆ a 1921     ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ American   ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ sil…       ┆            ┆            ┆        │
│ tt0012364  ┆ The Phantom ┆ 1921 ┆ None|Swedi ┆ … ┆ The        ┆ null       ┆ null       ┆ 1920   │
│            ┆ Carriage    ┆      ┆ sh         ┆   ┆ Phantom    ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ Carriage   ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ is a 1921… ┆            ┆            ┆        │
│ tt0013257  ┆ Häxan       ┆ 1922 ┆ Swedish|Da ┆ … ┆ Häxan is a ┆ 2000000    ┆ null       ┆ 1920   │
│            ┆             ┆      ┆ nish       ┆   ┆ 1922 Swedi ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ sh-Danish… ┆            ┆            ┆        │
│ tt0014429  ┆ Safety      ┆ 1923 ┆ English    ┆ … ┆ Safety     ┆ 121000     ┆ null       ┆ 1920   │
│            ┆ Last!       ┆      ┆            ┆   ┆ Last! is a ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ 1923       ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ America…   ┆            ┆            ┆        │
│ tt0014624  ┆ A Woman of  ┆ 1923 ┆ English    ┆ … ┆ A Woman of ┆ 351000     ┆ 634000     ┆ 1920   │
│            ┆ Paris: A    ┆      ┆            ┆   ┆ Paris is a ┆            ┆            ┆        │
│            ┆ Drama of F… ┆      ┆            ┆   ┆ 1923 sil…  ┆            ┆            ┆        │
│ …          ┆ …           ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …      │
│ tt27958252 ┆ Caught by   ┆ 2024 ┆ Mandarin|E ┆ … ┆ Caught by  ┆ null       ┆ null       ┆ 2020   │
│            ┆ the Tides   ┆      ┆ nglish     ┆   ┆ the Tides  ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ is a 2024  ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ …          ┆            ┆            ┆        │
│ tt28607951 ┆ Anora       ┆ 2024 ┆ English|Ru ┆ … ┆ Anora is a ┆ null       ┆ null       ┆ 2020   │
│            ┆             ┆      ┆ ssian|Arme ┆   ┆ 2024       ┆            ┆            ┆        │
│            ┆             ┆      ┆ nian       ┆   ┆ American   ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ roman…     ┆            ┆            ┆        │
│ tt28618488 ┆ Vermiglio   ┆ 2024 ┆ Italian|La ┆ … ┆ Vermiglio  ┆ null       ┆ null       ┆ 2020   │
│            ┆             ┆      ┆ tin        ┆   ┆ , also     ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ known as   ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ The …      ┆            ┆            ┆        │
│ tt32085997 ┆ Misericordi ┆ 2024 ┆ French     ┆ … ┆ Misericord ┆ null       ┆ null       ┆ 2020   │
│            ┆ a           ┆      ┆            ┆   ┆ ia is a    ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ 2024 black ┆            ┆            ┆        │
│            ┆             ┆      ┆            ┆   ┆ c…         ┆            ┆            ┆        │
│ tt32086077 ┆ All We      ┆ 2024 ┆ Malayalam| ┆ … ┆ All We     ┆ null       ┆ null       ┆ 2020   │
│            ┆ Imagine as  ┆      ┆ Hindi|Mara ┆   ┆ Imagine as ┆            ┆            ┆        │
│            ┆ Light       ┆      ┆ thi|Englis ┆   ┆ Light is a ┆            ┆            ┆        │
│            ┆             ┆      ┆ …          ┆   ┆ 2…         ┆            ┆            ┆        │
└────────────┴─────────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴────────┘

9. Now, find the count/sample size for how many films in the collection were released in each decade.

In [40]:
(
    dat
    .with_columns(decade = c.year // 10 * 10)
    .group_by(c.decade)
    .agg(
        num_movie = pl.len()
    )
)

shape: (11, 2)
┌────────┬───────────┐
│ decade ┆ num_movie │
│ ---    ┆ ---       │
│ i64    ┆ u32       │
╞════════╪═══════════╡
│ 1920   ┆ 19        │
│ 1960   ┆ 303       │
│ 1970   ┆ 232       │
│ 1980   ┆ 171       │
│ 1990   ┆ 154       │
│ …      ┆ …         │
│ 2020   ┆ 47        │
│ 1930   ┆ 119       │
│ 1940   ┆ 122       │
│ 1950   ┆ 162       │
│ 2010   ┆ 55        │
└────────┴───────────┘

10. Find the directors with more than 5 films in their collection, showing their average IMDB rating. Sort the results so the highest-rated directors appear at the top.

In [28]:
(
    dat
    .sort(c.rating_imdb, descending = True)
    .group_by(c.director)
    .agg(
        num_movie = pl.len(),
        avg_rating = c.rating_imdb.mean()
    )
    .filter(c.num_movie > 5)
)

shape: (48, 3)
┌─────────────────────────────────┬───────────┬────────────┐
│ director                        ┆ num_movie ┆ avg_rating │
│ ---                             ┆ ---       ┆ ---        │
│ str                             ┆ u32       ┆ f64        │
╞═════════════════════════════════╪═══════════╪════════════╡
│ Akira Kurosawa                  ┆ 24        ┆ 7.525      │
│ Michelangelo Antonioni          ┆ 7         ┆ 7.414286   │
│ Michael Powell|Emeric Pressbur… ┆ 7         ┆ 7.657143   │
│ Ernst Lubitsch                  ┆ 8         ┆ 7.375      │
│ Kenji Mizoguchi                 ┆ 9         ┆ 7.777778   │
│ …                               ┆ …         ┆ …          │
│ Alfred Hitchcock                ┆ 7         ┆ 7.528571   │
│ Yasujirô Ozu                    ┆ 20        ┆ 7.62       │
│ Terry Gilliam                   ┆ 6         ┆ 7.15       │
│ Samuel Fuller                   ┆ 7         ┆ 7.171429   │
│ John Cassavetes                 ┆ 7         ┆ 7.5        │
└─────────────────────────────────┴───────────┴────────────┘

11. Continuing, for each director with more than 5 films in their collection, show their highest-rated film. Hint: If you sort by rating before grouping, the first title in each group will be that director's highest-rated film.

In [25]:
(
    dat
    .sort(c.rating_imdb, descending = True)
    .group_by(c.director)
    .agg(
        num_movie = pl.len(),
        highest_imdb = c.title.first()
    )
    .filter(c.num_movie > 5)
)

shape: (48, 3)
┌─────────────────────────────────┬───────────┬─────────────────────────────┐
│ director                        ┆ num_movie ┆ highest_imdb                │
│ ---                             ┆ ---       ┆ ---                         │
│ str                             ┆ u32       ┆ str                         │
╞═════════════════════════════════╪═══════════╪═════════════════════════════╡
│ Louis Malle                     ┆ 13        ┆ Au Revoir les Enfants       │
│ Michael Powell|Emeric Pressbur… ┆ 7         ┆ The Red Shoes               │
│ Michael Haneke                  ┆ 6         ┆ The Seventh Continent       │
│ Keisuke Kinoshita               ┆ 7         ┆ Twenty-Four Eyes            │
│ John Cassavetes                 ┆ 7         ┆ A Woman Under the Influence │
│ …                               ┆ …         ┆ …                           │
│ Alfred Hitchcock                ┆ 7         ┆ Rebecca                     │
│ David Cronenberg                ┆ 7         ┆ A History of Violence       │
│ Carl Theodor Dreyer             ┆ 6         ┆ Ordet                       │
│ Jim Jarmusch                    ┆ 6         ┆ Down by Law                 │
│ Terry Gilliam                   ┆ 6         ┆ Brazil                      │
└─────────────────────────────────┴───────────┴─────────────────────────────┘

12. By default, only the first few rows of a result are displayed. To see more rows, we can pipe the result through the `print_rows` function. Modify your previous answer to display all of the results.

In [26]:
(
    dat
    .sort(c.rating_imdb, descending = True)
    .group_by(c.director)
    .agg(
        num_movie = pl.len(),
        highest_imdb = c.title.first()
    )
    .filter(c.num_movie > 5)
    .pipe(print_rows)
)

shape: (48, 3)
┌─────────────────────────────────┬───────────┬─────────────────────────────────┐
│ director                        ┆ num_movie ┆ highest_imdb                    │
│ ---                             ┆ ---       ┆ ---                             │
│ str                             ┆ u32       ┆ str                             │
╞═════════════════════════════════╪═══════════╪═════════════════════════════════╡
│ Samuel Fuller                   ┆ 7         ┆ Pickup on South Street          │
│ Masaki Kobayashi                ┆ 7         ┆ Harakiri                        │
│ Terry Gilliam                   ┆ 6         ┆ Brazil                          │
│ Michael Haneke                  ┆ 6         ┆ The Seventh Continent           │
│ David Lynch                     ┆ 6         ┆ Mulholland Drive                │
│ Wong Kar-Wai                    ┆ 7         ┆ In the Mood for Love            │
│ Yasujirô Ozu                    ┆ 20        ┆ Late Spring                     │
│ Michael Powell|Emeric Pressbur… ┆ 7         ┆ The Red Shoes                   │
│ Martin Scorsese                 ┆ 8         ┆ The Last Waltz                  │
│ Kenji Misumi                    ┆ 10        ┆ Lone Wolf and Cub: Baby Cart a… │
│ Kenji Mizoguchi                 ┆ 9         ┆ Sansho the Bailiff              │
│ Roberto Rossellini              ┆ 8         ┆ Rome, Open City                 │
│ Jacques Demy                    ┆ 6         ┆ The Umbrellas of Cherbourg      │
│ David Lean                      ┆ 7         ┆ Brief Encounter                 │
│ Richard Linklater               ┆ 6         ┆ Before Sunrise                  │
│ Federico Fellini                ┆ 7         ┆ La Strada                       │
│ Ernst Lubitsch                  ┆ 8         ┆ To Be or Not to Be              │
│ Akira Kurosawa                  ┆ 24        ┆ Seven Samurai                   │
│ Nagisa Ôshima                   ┆ 8         ┆ Death by Hanging                │
│ Koreyoshi Kurahara              ┆ 6         ┆ Intimidation                    │
│ Vittorio De Sica                ┆ 6         ┆ Bicycle Thieves                 │
│ François Truffaut               ┆ 7         ┆ The 400 Blows                   │
│ Alfred Hitchcock                ┆ 7         ┆ Rebecca                         │
│ Satyajit Ray                    ┆ 11        ┆ The World of Apu                │
│ Keisuke Kinoshita               ┆ 7         ┆ Twenty-Four Eyes                │
│ Pier Paolo Pasolini             ┆ 12        ┆ Accattone                       │
│ Jim Jarmusch                    ┆ 6         ┆ Down by Law                     │
│ John Cassavetes                 ┆ 7         ┆ A Woman Under the Influence     │
│ Jean Renoir                     ┆ 10        ┆ The Rules of the Game           │
│ David Cronenberg                ┆ 7         ┆ A History of Violence           │
│ Aki Kaurismäki                  ┆ 9         ┆ The Bohemian Life               │
│ Wes Anderson                    ┆ 10        ┆ The Grand Budapest Hotel        │
│ Mikio Naruse                    ┆ 6         ┆ When a Woman Ascends the Stair… │
│ Julien Duvivier                 ┆ 6         ┆ Panique                         │
│ Wim Wenders                     ┆ 12        ┆ Paris, Texas                    │
│ Robert Bresson                  ┆ 6         ┆ A Man Escaped                   │
│ Chantal Akerman                 ┆ 8         ┆ Jeanne Dielman, 23, quai du Co… │
│ Jean-Luc Godard                 ┆ 11        ┆ Vivre sa vie                    │
│ Ingmar Bergman                  ┆ 39        ┆ Scenes from a Marriage          │
│ Michelangelo Antonioni          ┆ 7         ┆ La Notte                        │
│ Carl Theodor Dreyer             ┆ 6         ┆ Ordet                           │
│ Seijun Suzuki                   ┆ 7         ┆ Youth of the Beast              │
│ Louis Malle                     ┆ 13        ┆ Au Revoir les Enfants           │
│ Agnès Varda                     ┆ 17        ┆ The Beaches of Agnès            │
│ Marlon Riggs                    ┆ 6         ┆ Ethnic Notions                  │
│ Rainer Werner Fassbinder        ┆ 10        ┆ Ali: Fear Eats the Soul         │
│ Abbas Kiarostami                ┆ 26        ┆ Close-Up                        │
│ Charles Chaplin                 ┆ 8         ┆ City Lights                     │
└─────────────────────────────────┴───────────┴─────────────────────────────────┘